---
- name: Create user systemd directory if necessary
  ansible.builtin.file:
    path: "{{ sysd_job__systemd_dir }}"
    recurse: true
    state: directory

- name: "Create systemd service file for {{ sysd_job__service }} job"
  ansible.builtin.template:
    src: "{{ sysd_job__service_template }}"
    dest: "{{ sysd_job__systemd_dir }}/{{ sysd_job__service }}.service"
    mode: u+rw

- name: "Create systemd timer file for {{ sysd_job__service }} job"
  ansible.builtin.template:
    src: "{{ sysd_job__timer_template }}"
    dest: "{{ sysd_job__systemd_dir }}/{{ sysd_job__service }}.timer"
    mode: u+rw

- name: Start and enable job timer
  ansible.builtin.systemd:
    name: "{{ sysd_job__service }}.timer"
    enabled: true
    state: started
    scope: user
    daemon_reload: true
