---
- name: pull api image
  containers.podman.podman_image:
    name: "{{ maw_api__image }}"

- name: create api dataprotection volume
  containers.podman.podman_volume:
    name: "{{ maw_api__dataprotection_volume }}"
    state: present
  register: _maw_api__dataprotection_volume_result

- name: restore dataprotection files
  ansible.builtin.include_role:
    name: podman_restore_volume
  when: >
    _maw_api__dataprotection_volume_result.changed
    and
    maw_api__restore_dataprotection
  vars:
    pod_vol_re__temp_remote_dir: "{{ maw_api__temp_dir }}"
    pod_vol_re__control_dir: "{{ maw_api__dataprotection_controller_backup_dir }}"
    pod_vol_re__volume: "{{ maw_api__dataprotection_volume }}"

- name: create uploads volume
  containers.podman.podman_volume:
    name: "{{ maw_api__upload_volume }}"
    state: present
  register: _maw_api__uploads_volume

- name: restore upload files
  ansible.builtin.include_role:
    name: podman_restore_volume
  when: >
    _maw_api__uploads_volume.changed
    and
    maw_api__restore_uploads
  vars:
    pod_vol_re__temp_remote_dir: "{{ maw_api__temp_dir }}"
    pod_vol_re__control_dir: "{{ maw_api__upload_controller_backup_dir }}"
    pod_vol_re__volume: "{{ maw_api__upload_volume }}"

- name: maw-api container
  containers.podman.podman_container:
    name: "{{ maw_api__container }}"
    pod: "{{ maw_api__pod }}"
    image: "{{ maw_api__image }}"
    state: started
    env_file: "{{ maw_api__envfile }}"
    security_opt:
      - label=disable
    volume:
      - "{{ maw_api__cert_volume }}:/certs:ro,z"
      - "{{ maw_api__dataprotection_volume }}:/dataprotection:rw,Z"
      - "{{ maw_api__upload_volume }}:/maw-uploads:rw,z"
      - "{{ maw_api__asset_dir_images }}:/srv/www/website_assets/images:ro"
    label:
      io.containers.autoupdate: image

- name: wait for api container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ maw_api__container }}"
