---
- name: prepare api environment file
  ansible.builtin.include_role:
    name: maw_envfile
  vars:
    maw_env__template: maw-api.env.j2
    maw_env__path: "{{ maw_api__envfile }}"
    maw_env__backup: "{{ maw_api__envfile_backup }}"

- name: configure natively hosted api site
  ansible.builtin.include_tasks:
    file: native_hosted.yml
  when: not maw_api__run_in_container

- name: configure container hosted api site
  ansible.builtin.include_tasks:
    file: container_hosted.yml
  when: maw_api__run_in_container
