---
argument_specs:
  main:
    short_description: Role to configure a systemd service and timer to delete old postgres backup files
    options:
      pg_clean__systemd_dir:
        type: str
        required: true
        description: the directory where to write the systemd service and timer files

      pg_clean__service:
        type: str
        required: true
        description: the name of the service

      pg_clean__pod:
        type: str
        required: true
        description: the name of the pod to run this container in

      pg_clean__volume:
        type: str
        required: true
        description: the name of the volume containing backups

      pg_clean__postgres_image:
        type: str
        required: true
        description: the name of the postgres docker image

      pg_clean__calendar:
        type: str
        required: true
        description: the systemd calendar specification to define when this job runs
