---
- name: Configure mikeandwan.us dev environment
  hosts: mawus_dev
  vars_files:
    - "{{ controller_secrets_file }}"

  tasks:
    - name: Install Prerequisites
      become: true
      ansible.builtin.dnf:
        state: present
        name:
          - buildah
          - dotnet
          - git
          - nodejs

    - name: Initialize podman
      ansible.builtin.include_role:
        name: podman_init
      vars:
        podman_users:
          - "{{ mawus_config_dev.service_account }}"

    - name: Ensure git directory exists
      ansible.builtin.file:
        path: "{{ git_root }}"
        state: directory
        mode: u+rwx

    - name: Get status of mikeandwan.us git directory
      ansible.builtin.stat:
        name: "{{ git_root }}/mikeandwan.us"
      register: maw_git_status

    - name: Clone mikeandwan.us
      ansible.builtin.git:
        dest: "{{ git_root }}/mikeandwan.us"
        repo: git@github.com:AerisG222/mikeandwan.us.git
        version: dev
      when: not maw_git_status.stat.exists

    # todo:
    #   - run npm install
    #   - build client assets (www/auth)
    #   - build client apps
    #   - build dotnet application
    #   - ...

    - name: Configure mikeandwan.us
      ansible.builtin.include_role:
        name: mikeandwan_us
      vars:
        mawus_config: "{{ mawus_config_dev }}"
