---
- name: Configure mikeandwan.us prod environment
  hosts: maw_prod
  vars_files:
    - "{{ controller_secrets_file }}"

  tasks:
    - name: Configure Base
      ansible.builtin.include_role:
        name: fedora_base

    - name: Configure sshd
      ansible.builtin.include_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
          - "{{ maw_host__username }}"

    - name: Configure mikeandwan.us
      ansible.builtin.include_role:
        name: mikeandwan_us
