---
- name: Configure mikeandwan.us test environment
  hosts: maw_test
  vars_files:
    - "{{ controller_secrets_file }}"

  tasks:

    - name: Configure mikeandwan.us
      ansible.builtin.include_role:
        name: mikeandwan_us
