---
- name: Configure mikeandwan.us
  hosts: maw
  vars_files:
    - "{{ controller_secrets_file }}"
    - vars/maw_vars.yml

  tasks:
    - name: Configure Base
      ansible.builtin.include_role:
        name: fedora_base

    - name: Configure sshd
      ansible.builtin.include_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
          - "{{ maw_host__username }}"
      when: ansible_connection != 'local'

    - name: Configure development environment for mikeandwan.us
      ansible.builtin.include_role:
        name: maw_dev_prep
      when: maw_dev_prep__configure_tools

    # - name: Configure mikeandwan.us
    #   ansible.builtin.include_role:
    #     name: mikeandwan_us
