---
- name: Gather current production backups
  hosts: maw_current_prod
  vars_files:
    - "{{ controller_secrets_file }}"
    - vars/maw_vars.yml

  tasks:
    - name: backup postgres roles and databases
      ansible.builtin.include_role:
        name: maw_prod_postgres_backup
      vars:
        ansible_user: "{{ maw_current__prod_username }}"

    - name: backup gdrive credentials volume
      ansible.builtin.include_role:
        name: maw_prod_gdrive_creds_backup
      vars:
        ansible_user: "{{ maw_current__prod_username }}"

    - name: backup google credentials volume
      ansible.builtin.include_role:
        name: maw_prod_google_creds_backup
      vars:
        ansible_user: "{{ maw_current__prod_username }}"

    - name: backup files in uploads volume
      ansible.builtin.include_role:
        name: maw_prod_uploads_backup
      vars:
        ansible_user: "{{ maw_current__prod_username }}"
      when: maw__do_uploads_backup


- name: Prepare host
  hosts: maw
  become: true
  vars_files:
    - "{{ controller_secrets_file }}"
    - vars/maw_vars.yml

  tasks:
    - name: Configure Base OS
      ansible.builtin.include_role:
        name: fedora_base

    - name: Add Service Account
      ansible.builtin.user:
        name: "{{ maw_host__username }}"
        password: "{{ maw_host__password | password_hash('sha512') }}"
        update_password: on_create
        state: present

    - name: Configure sshd
      ansible.builtin.import_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
          - "{{ maw_host__username }}"
      when: ansible_connection != 'local'

    - name: Initialize podman
      ansible.builtin.include_role:
        name: podman_init
      vars:
        pod_init__linger_users:
          - "{{ maw_host__username }}"


- name: Configure mikeandwan.us
  hosts: maw
  vars_files:
    - "{{ controller_secrets_file }}"
    - vars/maw_vars.yml

  tasks:
    # - name: Configure development environment for mikeandwan.us
    #   ansible.builtin.include_role:
    #     name: maw_dev_prep
    #   when: maw_dev_prep__configure_tools

    # - name: Configure mikeandwan.us
    #   ansible.builtin.include_role:
    #     name: mikeandwan_us
