---
- name: Configure mikeandwan.us test environment
  hosts: maw_test
  vars_files:
    - "{{ controller_secrets_file }}"

  tasks:

    - name: Initialize podman
      ansible.builtin.include_role:
        name: podman_init
      vars:
        pod_init__linger_users:
          - "{{ mawus__username }}"

    - name: Configure mikeandwan.us
      ansible.builtin.include_role:
        name: mikeandwan_us
