---
- name: Configure ddclient Servers
  hosts: ddclient
  vars_files:
    - "{{ ddclient_secrets_file }}"

  tasks:
    - name: Configure Base
      ansible.builtin.include_role:
        name: fedora_base

    - name: Configure Service Accounts
      ansible.builtin.include_role:
        name: service_accounts
      vars:
        service_accounts:
          - "{{ ddclient_config.service_account }}"

    - name: Configure sshd
      ansible.builtin.import_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
          - "{{ ddclient_config.service_account.username }}"

    - name: Initialize podman
      ansible.builtin.include_role:
        name: podman_init
      vars:
        podman_users:
          - "{{ ddclient_config.service_account }}"

    - name: Configure ddclient
      ansible.builtin.include_role:
        name: ddclient
        apply:
          become: true
          become_user: "{{ ddclient_config.service_account.username }}"
