---
- name: Configure mikeandwan.us prod environment
  hosts: mawus_prod
  vars_files:
    - "{{ controller_secrets_file }}"

  tasks:
    - name: Configure Base
      ansible.builtin.include_role:
        name: fedora_base

    - name: Add Service Accounts
      become: true
      ansible.builtin.user:
        name: "{{ mawus__username }}"
        password: "{{ mawus__password | password_hash('sha512') }}"
        update_password: always
        state: present

    - name: Configure firewall
      ansible.builtin.include_role:
        name: firewall
      vars:
        fw__allowed_services:
          - http
          - https

    - name: Configure sshd
      ansible.builtin.include_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
          - "{{ mawus__username }}"

    - name: Initialize podman
      ansible.builtin.include_role:
        name: podman_init
      vars:
        pod_init__linger_users:
          - "{{ mawus__username }}"

    - name: Configure mikeandwan.us
      ansible.builtin.include_role:
        name: mikeandwan_us
