---
- name: Configure ddclient Servers
  hosts: ddclient
  vars_files:
    - "{{ dd__secrets_file }}"

  tasks:
    - name: Configure Base
      ansible.builtin.include_role:
        name: fedora_base

    - name: Add Service Account
      become: true
      ansible.builtin.user:
        name: "{{ dd__username }}"
        password: "{{ dd__password | password_hash('sha512') }}"
        update_password: always
        state: present

    - name: Configure sshd
      ansible.builtin.import_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
          - "{{ dd__username }}"

    - name: Initialize podman
      ansible.builtin.include_role:
        name: podman_init
      vars:
        pod_init__linger_users:
          - "{{ dd__username }}"

    - name: Configure ddclient
      ansible.builtin.include_role:
        name: ddclient
        apply:
          become: true
          become_user: "{{ dd__username }}"
