---
- name: Gather current production backups
  hosts: maw_current_prod
  tags: maw_backups
  vars_files:
    - "{{ controller_secrets_file }}"
    - vars/maw_vars.yml
  vars:
    ansible_user: "{{ maw_current__prod_username }}"

  tasks:
    - name: Execute Backups
      ansible.builtin.include_role:
        name: maw_backup


- name: Prepare host
  hosts: maw
  become: true
  tags: maw_host
  vars_files:
    - "{{ controller_secrets_file }}"
    - vars/maw_vars.yml

  tasks:
    - name: Configure Host
      ansible.builtin.include_role:
        name: maw_host


- name: Configure mikeandwan.us
  hosts: maw
  tags: maw_services
  vars_files:
    - "{{ controller_secrets_file }}"
    - vars/maw_vars.yml

  tasks:
    # - name: Configure development environment for mikeandwan.us
    #   ansible.builtin.include_role:
    #     name: maw_dev_prep
    #   when: maw_dev_prep__configure_tools

    # - name: Configure mikeandwan.us
    #   ansible.builtin.include_role:
    #     name: maw
    #   vars:
    #     ansible_user: "{{ maw_host__username }}"
