---
- name: Configure mikeandwan.us prod environment
  hosts: mawus_prod
  vars_files:
    - "{{ external_vars_file }}"

  tasks:
    - name: Configure Base
      ansible.builtin.include_role:
        name: fedora_base

    - name: Configure Service Accounts
      ansible.builtin.include_role:
        name: service_accounts
      vars:
        service_accounts:
          - "{{ mawus_config_prod.service_account }}"

    - name: Configure firewall
      ansible.builtin.include_role:
        name: firewall
      vars:
        firewall_allowed_services:
          - http
          - https

    - name: Configure sshd
      ansible.builtin.include_role:
        name: sshd
      vars:
        sshd_allow_users:
          - "{{ ansible_user }}"
          - "{{ mawus_config_prod.service_account.username }}"

    - name: Initialize podman
      ansible.builtin.include_role:
        name: podman_init
      vars:
        podman_users:
          - "{{ mawus_config_prod.service_account }}"

    - name: Configure mikeandwan.us
      ansible.builtin.include_role:
        name: mikeandwan_us
      vars:
        mawus_config: "{{ mawus_config_prod }}"
