- name: see if we already have google creds backups
  block:
    - name: look for credentials backup
      ansible.builtin.stat:
        path: "{{ maw_prod_google_creds_bu__control_dir }}/www_emailer.json"
      register: _maw_prod_google_creds_bu__credentials_result
      delegate_to: localhost
  when: maw_prod_google_creds_bu__use_existing_backups

- name: perform backup if needed
  ansible.builtin.include_role:
    name: podman_backup_volume
  vars:
    podman_vol_bu__hostname: "{{ maw_prod_google_creds_bu__hostname }}"
    podman_vol_bu__username: "{{ maw_prod_google_creds_bu__username }}"
    podman_vol_bu__volume: "{{ maw_prod_google_creds_bu__volume }}"
    podman_vol_bu__control_dir: "{{ maw_prod_google_creds_bu__control_dir }}"
    podman_vol_bu__temp_remote_dir: "{{ maw_prod_google_creds_bu__temp_remote_dir }}"
  when: >
    (not maw_prod_google_creds_bu__use_existing_backups)
    or
    (
      (not _maw_prod_google_creds_bu__credentials_result.stat.exists)
      and
      (not _maw_prod_google_creds_bu__token_result.stat.exists)
    )
