---
- name: Set hostname
  when: hostname | length > 0 and domain | length > 0
  become: yes
  hostname:
    name: '{{ hostname }}.{{ domain }}'
    use: systemd

- name: Add SSH public keys
  authorized_key:
    user: mmorano
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub')) }}"
