---
- name: pull auth image
  containers.podman.podman_image:
    name: "{{ maw_auth__image }}"

- name: create auth dataprotection volume
  containers.podman.podman_volume:
    name: "{{ maw_auth__dataprotection_volume }}"
    state: present
  register: _maw_auth__dataprotection_volume_result

- name: restore dataprotection files
  ansible.builtin.include_role:
    name: podman_restore_volume
  when: >
    _maw_auth__dataprotection_volume_result.changed
    and
    maw_auth__restore_dataprotection
  vars:
    pod_vol_re__temp_remote_dir: "{{ maw_auth__temp_dir }}"
    pod_vol_re__control_dir: "{{ maw_auth__dataprotection_controller_backup_dir }}"
    pod_vol_re__volume: "{{ maw_auth__dataprotection_volume }}"

- name: maw-auth container
  containers.podman.podman_container:
    name: "{{ maw_auth__container }}"
    pod: "{{ maw_auth__pod }}"
    image: "{{ maw_auth__image }}"
    state: started
    env_file: "{{ maw_auth__envfile }}"
    volume:
      - "{{ maw_auth__cert_volume }}:/certs:ro,z"
      - "{{ maw_auth__dataprotection_volume }}:/dataprotection:rw,Z"
      - "{{ maw_auth__google_creds_volume }}:/google-creds:ro,z"
    label:
      io.containers.autoupdate: image

- name: wait for auth container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ maw_auth__container }}"
