---
- name: prepare auth environment file
  ansible.builtin.include_role:
    name: maw_envfile
  vars:
    maw_env__template: maw-auth.env.j2
    maw_env__path: "{{ maw_auth__envfile }}"
    maw_env__backup: "{{ maw_auth__envfile_backup }}"

- name: configure natively hosted api site
  ansible.builtin.include_tasks:
    file: native_hosted.yml
  when: maw_auth__image | length == 0

- name: configure container hosted api site
  ansible.builtin.include_tasks:
    file: container_hosted.yml
  when: maw_auth__image | length > 0
