---
- name: prepare auth environment file
  ansible.builtin.include_role:
    name: maw_envfile
  vars:
    mawus_env__template: maw-auth.env.j2
    mawus_env__path: "{{ mawus_auth__envfile }}"
    mawus_env__backup: "{{ mawus_auth__envfile_backup }}"

- name: configure natively hosted api site
  ansible.builtin.include_tasks:
    file: native_hosted.yml
  when: mawus_auth__image | length == 0

- name: configure container hosted api site
  ansible.builtin.include_tasks:
    file: container_hosted.yml
  when: mawus_auth__image | length > 0
