---
- name: create gdrive-creds volume
  containers.podman.podman_volume:
    name: "{{ maw_postgres__gdrive_creds_volume }}"
    state: present
  register: _maw_postgres__gdrive_creds_volume_result

- name: restore maw-gdrive-creds
  ansible.builtin.include_role:
    name: podman_restore_volume
  when: maw_postgres__configure_archive_jobs and _maw_postgres__gdrive_creds_volume_result.changed
  vars:
    pod_vol_re__temp_remote_dir: "{{ maw_postgres__tempdir }}"
    pod_vol_re__control_dir: "{{ maw_prod_gdrive_creds_bu__control_dir }}"
    pod_vol_re__volume: "{{ maw_postgres__gdrive_creds_volume }}"
