---
argument_specs:
  main:
    short_description: Configures ddclient to run periodically in a container
    options:
      dd__tmp_dir:
        type: str
        required: true
        description: the directory to write the temp dd_client.conf to so that it can then be copied to a volume.

      dd__systemd_dir:
        type: str
        required: true
        description: the directory to store systemd service files

      dd__pod:
        type: str
        default: ddclient-pod
        description: the pod name to run the ddclient container in

      dd__container:
        type: str
        default: ddclient-container
        description: the name for the ddclient container

      dd__volume:
        type: str
        default: ddclient-config
        description: the name of the volume to use for ddclient config files

      dd__namecheap_password:
        type: str
        required: true
        description: the password / api key for updating dns
