---
argument_specs:
  main:
    short_description: Role to configure a systemd service and timer to run the reverse geocode process
    options:
      maw_revgeo__systemd_dir:
        type: str
        required: true
        description: the directory where to write the systemd service and timer files

      maw_revgeo__service:
        type: str
        required: true
        description: the name of the service

      maw_revgeo__pod:
        type: str
        required: true
        description: the name of the pod in which to run the reverse geocode service

      maw_revgeo__image:
        type: str
        required: true
        description: the name of docker image for the reverse geocode process

      maw_revgeo__volume:
        type: str
        required: true
        description: the name of the volume in which to write reverse geocode results

      maw_revgeo__envfile:
        type: str
        required: true
        description: the name of the file containing necessary environment variables for the reverse geocode process

      maw_revgeo__envfile_backup:
        type: str
        required: true
        description: indicates if the envfile should be backed up before being overwritten

      maw_revgeo__calendar:
        type: str
        required: true
        description: the systemd calendar specification to define when this job runs

      maw_revgeo__restore:
        type: bool
        required: true
        description: indicates if the contents of the reverse geocoder volume should be restored in the new volume

      maw_revgeo__temp_dir:
        type: str
        required: true
        description: a directory on the remote where files can be temporarily stored before being placed in a volume

      maw_revgeo__controller_backup_dir:
        type: str
        required: true
        description: directory on the controller where the revgeo data should be backed up
