---
- name: Update Package Metadata and Packages
  become: yes
  dnf:
    update_cache: yes
    state: present

- name: Install Packages
  become: yes
  dnf:
    state: present
    name:
      - dnf-plugin-system-upgrade
      - podman

- name: Allow inbound HTTP/HTTPS traffic
  become: yes
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item }}"
    state: enabled
    zone: FedoraServer
  loop:
    - http
    - https
