---
- name: "Temporarily set SSH username to {{ mawus_svc_account }}"
  ansible.builtin.set_fact:
    orig_ansible_user: "{{ ansible_user }}"
    ansible_user: "{{ mawus_svc_account }}"
    mawus_podname: maw-pod
  changed_when: false
  delegate_to: localhost

- name: show maw svc user
  ansible.builtin.command: whoami

- name: "Reset SSH username to {{ orig_ansible_user }}"
  ansible.builtin.set_fact:
    ansible_user: "{{ orig_ansible_user }}"
  changed_when: false
  delegate_to: localhost
