---
- name: Install Packages
  become: yes
  ansible.builtin.dnf:
    state: present
    name:
      - podman

- name: Configure subuid and subgid
  become: yes
  ansible.builtin.command:
    argv:
      - usermod
      - --add-subuids
      - "{{ item.subuid }}"
      - --add-subgids
      - "{{ item.subgid }}"
      - "{{ item.username }}"
  loop: "{{ service_accounts if service_accounts is iterable else [] }}"
  when: item.use_podman
