---
# https://stackoverflow.com/questions/52668990/ansible-copy-files-to-docker-volume
- name: create temporary data-only container
  containers.podman.podman_container:
    name: temp_data_container
    image: docker.io/tianon/true
    state: present
    volumes:
    - "{{ volume }}:/data"

- name: copy file(s) to volume
  ansible.builtin.command:
    argv:
      - podman
      - cp
      - "{{ file }}"
      - temp_data_container:/data

- name: stop data only container
  containers.podman.podman_container:
    name: temp_data_container
    state: absent