---
- name: Add Service Accounts
  become: yes
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: always
    state: present
  loop: "{{ service_accounts if service_accounts is iterable else [] }}"
