---
- name: Add Service Accounts
  become: yes
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: always
    state: present
  loop: "{{ service_accounts if service_accounts is iterable else [] }}"

- name: add ssh public keys
  become: yes
  ansible.builtin.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
  loop: "{{ service_accounts if service_accounts is iterable else [] }}"
  when: item.allow_ssh

# todo: naive approach below will duplicate usernames each time this is run
- name: add user to sshd AllowUsers
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    backup: yes
    backrefs: yes
    regex: "^AllowUsers\\s+(.*)$"
    line: "AllowUsers \\1 {{ item.username }}"
    state: present
    validate: sshd -t -f %s
  loop: "{{ service_accounts if service_accounts is iterable else [] }}"
  when: item.allow_ssh
  notify:
    - "reload_sshd"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
