---
# https://stackoverflow.com/questions/52668990/ansible-copy-files-to-docker-volume
- name: create temporary data-only container
  containers.podman.podman_container:
    name: temp_data_container
    image: docker.io/tianon/true
    state: present
    volumes:
    - "{{ pod_cfv__volume }}:/data"

- name: copy file(s) from volume
  ansible.builtin.command:
    argv:
      - podman
      - cp
      - "temp_data_container:/data/{{ pod_cfv__src_path }}"
      - "{{ pod_cfv__dest_relative_path }}"

- name: stop data only container
  containers.podman.podman_container:
    name: temp_data_container
    state: absent
