---
ansible_host: 192.168.122.138
ansible_user: mmorano

# base
hostname: lvmtest
update_packages: no

# ddclient
ddclient_config:
  service_account:
    username: svc_ddclient
    password: "{{ vault_password_lvmtest_svc_ddclient }}"
    groups:
    subuid: 200000-265536
    subgid: 200000-265536
    enable_linger: true
  namecheap_password: "{{ vault_namecheap_password }}"
