---
ansible_host: 192.168.122.138
ansible_user: mmorano

# base
fed_b__hostname: lvmtest

# ddclient
dd__tmp_dir: /home/svc_ddclient
dd__systemd_dir: /home/svc_ddclient/.config/systemd/user
dd__namecheap_password: "{{ vault_namecheap_password }}"

ddclient_config:
  service_account:
    username: svc_ddclient
    password: "{{ vault_password_lvmtest_svc_ddclient }}"
    groups:
    subuid: 200000-265536
    subgid: 200000-265536
    enable_linger: true
