ansible_user: mmorano

hostname: tifa

external_vars_root: "{{ lookup('env', 'HOME') }}/ansible/{{ hostname }}"
ddclient_secrets_file: "{{ external_vars_root }}/ddclient_secrets.yml"

# -------------------------------------
# ddclient
# -------------------------------------
ddclient_config:
  service_account:
    username: svc_ddclient
    password: "{{ vault_password_svc_ddclient }}"
    groups:
    subuid: 300000-365536
    subgid: 300000-365536
    enable_linger: true
  podman_podname: ddclient-pod
  podman_container_name: ddclient-container
  namecheap_password: "{{ vault_namecheap_password }}"
