ansible_host: 192.168.122.245
ansible_user: mmorano

# base
hostname: vmtest2
update_packages: no

external_vars_root: "{{ lookup('env', 'HOME') }}/ansible/hosts/{{ hostname }}"
ddclient_secrets_file: "{{ external_vars_root }}/ddclient_secrets.yml"

# -------------------------------------
# ddclient
# -------------------------------------
dd__tmp_dir: /home/svc_ddclient
dd__systemd_dir: /home/svc_ddclient/.config/systemd/user
dd__namecheap_password: "{{ vault_namecheap_password }}"

ddclient_config:
  service_account:
    username: svc_ddclient
    password: "{{ vault_password_svc_ddclient }}"
    groups:
    subuid: 300000-365536
    subgid: 300000-365536
    enable_linger: true
