---
hostname: vmwstest

update_packages: true
android_studio: true
aws_cli: true
azure_cli: true
azure_data_studio: no
google_chrome: true
google_earth: true
ms_teams: true
powershell: true
vscode: true
