---
- name: Make sure maw_env directory exists
  ansible.builtin.file:
    path: "{{ maw_env__path | dirname }}"
    state: directory
    mode: u+rwx

- name: Prepare environment files
  ansible.builtin.template:
    backup: "{{ maw_env__backup }}"
    src: "{{ maw_env__template }}"
    dest: "{{ maw_env__path }}"
    mode: u+rw
