---
- name: prepare google credential volume
  ansible.builtin.include_tasks:
    file: volume.yml
  when: maw_google_creds__use_volume

- name: prepare google credential directory
  ansible.builtin.include_tasks:
    file: directory.yml
  when: not maw_google_creds__use_volume
