---
argument_specs:
  main:
    short_description: Role to configure a systemd service and timer to backup postgres roles
    options:
      pg_bu_roles__systemd_dir:
        type: str
        required: true
        description: the directory where to write the systemd service and timer files

      pg_bu_roles__service:
        type: str
        required: true
        description: the name of the service

      pg_bu_roles__pod:
        type: str
        required: true
        description: the name of the pod to run this container in

      pg_bu_roles__volume:
        type: str
        required: true
        description: the name of the volume where backups will be written

      pg_bu_roles__envfile:
        type: str
        required: true
        description: the path to the environment file containing the postgres user password

      pg_bu_roles__postgres_image:
        type: str
        required: true
        description: the name of the postgres docker image

      pg_bu_roles__calendar:
        type: str
        required: true
        description: the systemd calendar specification to define when this job runs
