---
- name: set internal src variable for local connections
  ansible.builtin.set_fact:
    internal_podman_copy_src_path: "{{ podman_copy_src_path }}"
  when: ansible_connection == 'local'

- name: copy files to remote if needed
  block:

    - name: create remote temp dir
      ansible.builtin.file:
        path: "{{ podman_copy_remote_temp_dir }}"
        state: directory
        mode: u+rwx

    - name: copy file(s) to remote temp dir
      ansible.builtin.copy:
        remote_src: "{{ podman_copy_remote_src }}"
        src: "{{ podman_copy_src_path }}"
        dest: "{{ podman_copy_remote_temp_dir }}"

    - name: update src_path with remote temp file path
      ansible.builtin.set_fact:
        internal_podman_copy_src_path: "{{ podman_copy_remote_temp_dir }}/{{ podman_copy_src_path | basename }}"

  when: ansible_connection != 'local'

# https://stackoverflow.com/questions/52668990/ansible-copy-files-to-docker-volume
- name: create temporary data-only container
  containers.podman.podman_container:
    name: temp_data_container
    image: docker.io/tianon/true
    state: present
    volumes:
    - "{{ podman_copy_volume_name }}:/data"

- name: copy file(s) to volume
  ansible.builtin.command:
    argv:
      - podman
      - cp
      - "{{ internal_podman_copy_src_path }}"
      - "temp_data_container:/data/{{ podman_copy_dest_relative_path }}"

- name: stop data only container
  containers.podman.podman_container:
    name: temp_data_container
    state: absent

- name: create remote temp dir
  ansible.builtin.file:
    path: "{{ podman_copy_remote_temp_dir }}"
    state: absent
  when: ansible_connection != 'local'
