- name: set role password
  containers.podman.podman_container:
    name: "{{ pg_res_role__temp_container }}"
    pod: "{{ pg_res_role__pod }}"
    image: "{{ pg_res_role__image }}"
    env_file: "{{ pg_res_role__envfile }}"
    interactive: true
    state: started
    command:
      - psql
      - '-h'
      - 127.0.0.1
      - '-U'
      - postgres
      - '-d'
      - postgres
      - '-c'
      - "ALTER ROLE {{ _pg_res_role__role_info.username }} WITH PASSWORD '{{ _pg_res_role__role_info.password }}';"

- name: wait for set role container to stop
  ansible.builtin.include_role:
    name: podman_wait_for_stop
  vars:
    pod_stop__container_name: "{{ pg_res_role__temp_container }}"
    pod_stop__result_varname: role_pwd_result

- name: fail if password not set
  ansible.builtin.fail:
    msg: role passwords not properly set
  failed_when: role_pwd_result | int != 0
