---
- name: Install Packages
  become: yes
  ansible.builtin.dnf:
    state: present
    name:
      - podman

- name: Configure subuid and subgid
  become: yes
  ansible.builtin.command:
    argv:
      - usermod
      - --add-subuids
      - "{{ item.subuid }}"
      - --add-subgids
      - "{{ item.subgid }}"
      - "{{ item.username }}"
  loop_control:
    label: "{{ item.username }}"
  loop: "{{ podman_users if podman_users is iterable else [] }}"

- name: Enable linger for rootless containers
  become: yes
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ item.username }}
  loop_control:
    label: "{{ item.username }}"
  loop: "{{ podman_users if podman_users is iterable else [] }}"
