---
argument_specs:
  main:
    short_description: Creates the maw files container
    options:
      maw_files__pod:
        type: str
        required: true
        description: The name of the pod in which to run the files container

      maw_files__image:
        type: str
        required: true
        description: The full name of the docker image

      maw_files__container:
        type: str
        required: true
        description: The name to give the running maw-files container

      maw_files__cert_volume:
        type: str
        required: true
        description: The name of the volume containing the internal certificates
