---
argument_specs:
  main:
    short_description: Creates auth service and supporting objects for mikeandwan.us
    options:
      maw_auth__run_in_container:
        type: bool
        required: true
        description: Indicates if maw_auth should run in a container (we will run this manually for dev)

      maw_auth__pod:
        type: str
        required: true
        description: Name of the pod in which the auth container should run

      maw_auth__image:
        type: str
        required: true
        description: Fully qualified auth image to use

      maw_auth__container:
        type: str
        required: true
        description: Name of the container

      maw_auth__cert_dir:
        type: str
        required: true
        description: Local directory where the certificates are stored

      maw_auth__cert_volume:
        type: str
        required: true
        description: Name of the volume where certificates are stored

      maw_auth__dataprotection_dir:
        type: str
        required: true
        description: Full path to directory where dataprotection files will be written

      maw_auth__dataprotection_volume:
        type: str
        required: true
        description: Name of the volume where data protection files are stored

      maw_auth__envfile:
        type: str
        required: true
        description: Path to the auth environment file

      maw_auth__envfile_backup:
        type: bool
        required: true
        description: Indicates if the existing envfile should be backed up before being overwritten

      maw_auth__aspnet_env:
        type: str
        required: true
        description: Specifies the environment for the aspnet application

      maw_auth__google_creds_volume:
        type: str
        required: true
        description: The volume where the google credentials are stored

      maw_auth__google_email_creds_file:
        type: str
        required: true
        description: The path to the google credentials file

      maw_auth__pfx:
        type: str
        required: true
        description: Path to the auth pfx file

      maw_auth__pfx_pwd:
        type: str
        required: true
        description: The password for the auth pfx

      maw_auth__sql_username:
        type: str
        required: true
        description: The name of the user to connect to postgres

      maw_auth__sql_password:
        type: str
        required: true
        description: The password for the postgres user

      maw_auth__www_auth_client_secret:
        type: str
        required: true
        description: The client secret for the www site for OAuth

      maw_auth__google_plus_client_id:
        type: str
        required: true
        description: The google client id for OAuth

      maw_auth__google_plus_client_secret:
        type: str
        required: true
        description: The google client secret for OAuth

      maw_auth__twitter_client_id:
        type: str
        required: true
        description: The twitter client id for OAuth

      maw_auth__twitter_client_secret:
        type: str
        required: true
        description: The twitter client secret for OAuth

      maw_auth__microsoft_client_id:
        type: str
        required: true
        description: The microsoft client id for OAuth

      maw_auth__microsoft_client_secret:
        type: str
        required: true
        description: The microsoft client secret for OAuth

      maw_auth__github_client_id:
        type: str
        required: true
        description: The github client id for OAuth

      maw_auth__github_client_secret:
        type: str
        required: true
        description: The github client secret for OAuth

      maw_auth__pfx_signing:
        type: str
        required: true
        description: The certificate used for signing data in the app

      maw_auth__restore_dataprotection:
        type: bool
        required: true
        description: indicates if the dataprotection volume should be restored from backup

      maw_auth__dataprotection_controller_backup_dir:
        type: str
        required: true
        description: Absolute path to the directory on the controller that holds the api dataprotection backup

      maw_auth__temp_dir:
        type: str
        required: true
        description: Absolute path to a temp directory on the remote
