---
- name: Include maw_hostnames.yml
  ansible.builtin.include_tasks: maw_hostnames.yml
  loop:
    - mikeandwan.us
    - api.mikeandwan.us
    - auth.mikeandwan.us
    - files.mikeandwan.us
    - photos.mikeandwan.us
    - www.mikeandwan.us

- name: Include port_mapping.yml
  ansible.builtin.include_tasks: port_mapping.yml

- name: "Temporarily set SSH username to {{ mawus_svc_account }}"
  ansible.builtin.set_fact:
    orig_ansible_user: "{{ ansible_user }}"
    ansible_user: "{{ mawus_svc_account }}"
    mawus_podname: maw-pod
    redis_version: 6
    postgres_version: 14
    solr_version: 8
    env_file_dir: /home/svc_www_maw
  changed_when: false
  delegate_to: localhost

- name: Include maw_volumes.yml
  ansible.builtin.include_tasks: maw_volumes.yml

- name: Include maw_pod.yml
  ansible.builtin.include_tasks: maw_pod.yml

- name: Include maw_systemd.yml
  ansible.builtin.include_tasks: maw_systemd.yml

- name: "Reset SSH username to {{ orig_ansible_user }}"
  ansible.builtin.set_fact:
    ansible_user: "{{ orig_ansible_user }}"
  changed_when: false
  delegate_to: localhost
