---
- name: Initialize self signed certificates
  ansible.builtin.include_tasks:
    file: maw_certs.yml
    apply:
      become: true
      become_user: "{{ maw__username }}"

- name: Obtain self signed certificate passwords
  ansible.builtin.include_tasks:
    file: maw_certs_get_pwds.yml
    apply:
      become: true
      become_user: "{{ maw__username }}"

- name: Include maw_pod.yml
  ansible.builtin.include_tasks:
    file: maw_pod.yml
    apply:
      become: true
      become_user: "{{ maw__username }}"
