---
- name: Include maw_hostnames.yml
  ansible.builtin.include_tasks: maw_hostnames.yml
  loop:
    - "{{ mawus_config.fqdn_naked }}"
    - "{{ mawus_config.fqdn_api }}"
    - "{{ mawus_config.fqdn_auth }}"
    - "{{ mawus_config.fqdn_files }}"
    - "{{ mawus_config.fqdn_photos }}"
    - "{{ mawus_config.fqdn_www }}"

- name: Include port_mapping.yml
  ansible.builtin.include_tasks: port_mapping.yml
  when: mawus_config.allow_low_ports

- name: Initialize host directories
  ansible.builtin.include_tasks: maw_host_directories.yml
  vars:
    asset_dirs:
      - "{{ mawus_config.asset_dir_images }}"
      - "{{ mawus_config.asset_dir_movies }}"

- name: Include maw_admin_scripts.yml
  ansible.builtin.include_tasks:
    file: maw_admin_scripts.yml
    apply:
      become: true
      become_user: "{{ mawus_config.service_account.username }}"
  when: ansible_connection != 'local'

- name: Include maw_pull_images.yml
  ansible.builtin.include_tasks:
    file: maw_pull_images.yml
    apply:
      become: true
      become_user: "{{ mawus_config.service_account.username }}"

- name: Include maw_volumes_create.yml
  ansible.builtin.include_tasks:
    file: maw_volumes_create.yml
    apply:
      become: true
      become_user: "{{ mawus_config.service_account.username }}"

- name: Include maw_volumes_populate.yml
  ansible.builtin.include_tasks:
    file: maw_volumes_populate.yml
    apply:
      become: true
      become_user: "{{ mawus_config.service_account.username }}"

- name: Include maw_maintenance.yml
  ansible.builtin.include_tasks:
    file: maw_maintenance.yml
    apply:
      become: true
      become_user: "{{ mawus_config.service_account.username }}"

- name: Initialize self signed certificates
  ansible.builtin.include_tasks:
    file: maw_certs.yml
    apply:
      become: true
      become_user: "{{ mawus_config.service_account.username }}"

- name: Include maw_env_files.yml
  ansible.builtin.include_tasks:
    file: maw_env_files.yml
    apply:
      become: true
      become_user: "{{ mawus_config.service_account.username }}"

- name: Include maw_pod.yml
  ansible.builtin.include_tasks:
    file: maw_pod.yml
    apply:
      become: true
      become_user: "{{ mawus_config.service_account.username }}"
