---
- name: define temp dir var
  ansible.builtin.set_fact:
    maw_certs__tempdir: "{{ remote_home_dir }}/_tmp_ansible_cert_pwds"

- name: ensure temp dir exists
  ansible.builtin.file:
    path: "{{ maw_certs__tempdir }}"
    state: directory
    mode: u+rw

- name: copy certificate files from volume to server/host
  ansible.builtin.include_role:
    name: podman_copy
  vars:
    pod_cp__src_dir_or_volume: "{{ cert_vol }}"
    pod_cp__dest_dir_or_volume: "{{ maw_certs__tempdir }}"
    pod_cp__command: "cp /src/{{ item }} /dest"
  loop:
    - api/api.pfx.pwd
    - auth/auth.pfx.pwd
    - www/www.pfx.pwd

- name: get api cert pwd
  ansible.builtin.slurp:
    src: "{{ maw_certs__tempdir }}/api.pfx.pwd"
  register: api_pwd

- name: get auth cert pwd
  ansible.builtin.slurp:
    src: "{{ maw_certs__tempdir }}/auth.pfx.pwd"
  register: auth_pwd

- name: get www cert pwd
  ansible.builtin.slurp:
    src: "{{ maw_certs__tempdir }}/www.pfx.pwd"
  register: www_pwd

- name: set cert pwd variables
  ansible.builtin.set_fact:
    mawus__pfx_pwd_api: "{{ api_pwd.content | b64decode }}"
    mawus__pfx_pwd_auth: "{{ auth_pwd.content | b64decode }}"
    mawus__pfx_pwd_www: "{{ www_pwd.content | b64decode }}"

- name: delete temp dir
  ansible.builtin.file:
    path: "{{ maw_certs__tempdir }}"
    state: absent

  when: mawus__certs_dir | length == 0
