---
- name: set the volume source (local / non-container)
  ansible.builtin.set_fact:
    cert_vol: "{{ mawus_config.certs_dir }}"
  when: mawus_config.env == 'local'

- name: set the volume source (not local - container)
  ansible.builtin.set_fact:
    cert_vol: "{{ maw_cert_volume.volume.Name }}"
  when: mawus_config.env != 'local'

# todo: evaluate dev/prod support
- name: initialize local certs
  containers.podman.podman_container:
    name: maw-certs
    image: "docker.io/aerisg222/maw-certs:latest"
    state: started
    interactive: yes
    rm: yes
    tty: yes
    volume:
      - "{{ cert_vol }}:/certs:rw,z"

- name: wait for cert initialization to complete
  containers.podman.podman_container_info:
    name: maw-certs
  register: cert_container
  delay: 10
  retries: 24
  until: cert_container.containers | length == 0
