---
- name: Make sure admin_scripts directory exists
  ansible.builtin.file:
    path: "{{ remote_mawus_root }}/admin_scripts"
    state: directory
    mode: u+rwx

- name: Prepare scripts
  ansible.builtin.template:
    backup: "{{ mawus_config.env == 'prod' }}"
    src: "admin_scripts/{{ item }}.j2"
    dest: "{{ remote_mawus_root }}/admin_scripts/{{ item }}"
    mode: u+rwx
  loop:
    - idsrvsql.sh
    - wwwsql.sh
    - update-support-images.sh
