---
- name: Make sure maw_env directory exists
  ansible.builtin.file:
    path: "{{ mawus_config.podman_env_dir }}"
    state: directory

- name: Prepare environment files
  ansible.builtin.template:
    backup: yes
    src: "maw_env/{{ item.envfile }}.j2"
    dest: "{{ mawus_config.podman_env_dir }}/{{ item.envfile }}"
    mode: u+rw
  when: item.generate
  loop:
    - envfile: maw-postgres.env
      generate: yes
    - envfile: maw-api.env
      generate: "{{ mawus_config.env != 'local' }}"
    - envfile: maw-auth.env
      generate: "{{ mawus_config.env != 'local' }}"
    - envfile: maw-reverse-geocode.env
      generate: "{{ mawus_config.env != 'local' }}"
    - envfile: maw-www.env
      generate: "{{ mawus_config.env != 'local' }}"
