---
- name: create maw-pod pod
  containers.podman.podman_pod:
    name: "{{ mawus_podname }}"
    state: started

# redis
- name: create redis container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-redis
    image: "docker.io/redis:{{ redis_version }}-alpine"
    command: redis-server --save 60 1
    state: started
    volume:
      - "{{ redis_volume.volume.Name }}:/data:rw,z"
    label:
      io.containers.autoupdate: image

# postgres
- name: create postgres container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-postgres
    image: "docker.io/postgres:{{ postgres_version }}-alpine"
    state: started
    volume:
      - "{{ postgres_volume.volume.Name }}:/var/lib/postgresql/data:rw,z"
    label:
      io.containers.autoupdate: image

# solr
- name: create solr container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-solr
    image: "docker.io/solr:{{ solr_version }}"
    state: started
    volume:
      - "{{ solr_volume.volume.Name }}:/var/solr:rw,z"
    label:
      io.containers.autoupdate: image

# certs
# todo: evaluate dev/prod support
- name: initialize local certs
  containers.podman.podman_container:
    name: maw-certs
    image: "docker.io/aerisg222/maw-certs:latest"
    state: started
    rm: yes
    volume:
      - "{{ maw_cert_volume.volume.Name }}:/certs:rw,z"

# auth
- name: create maw-auth container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-auth
    image: "docker.io/aerisg222/maw-auth:latest"
    state: started
    env_file: "{{ env_file_dir }}/maw-auth.env"
    volume:
      - "{{ maw_cert_volume.volume.Name }}:/certs:ro,z"
      - "{{ auth_dataprotection_volume.volume.Name }}:/dataprotection:rw,Z"
      - "{{ google_creds_volume.volume.Name }}:/google-creds:ro,z"
    label:
      io.containers.autoupdate: image

# api
- name: create maw-api container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-api
    image: "docker.io/aerisg222/maw-api:latest"
    state: started
    env_file: "{{ env_file_dir }}/maw-api.env"
    security-opt:
      - label=disable
    volume:
      - "{{ maw_cert_volume.volume.Name }}:/certs:ro,z"
      - "{{ api_dataprotection_volume.volume.Name }}:/dataprotection:rw,Z"
      - "{{ uploads_volume.volume.Name }}:/maw-uploads:rw,z"
      - /srv/www/website_assets/images:/srv/www/website_assets/images:ro
    label:
      io.containers.autoupdate: image

# www
- name: create maw-www container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-www
    image: "docker.io/aerisg222/maw-www:latest"
    state: started
    env_file: "{{ env_file_dir }}/maw-www.env"
    security-opt:
      - label=disable
    volume:
      - "{{ maw_cert_volume.volume.Name }}:/certs:ro,z"
      - "{{ www_dataprotection_volume.volume.Name }}:/dataprotection:rw,Z"
      - "{{ google_creds_volume.volume.Name }}:/google-creds:ro,z"
      - /srv/www/website_assets/images:/srv/www/website_assets/images:ro
      - /srv/www/website_assets/movies:/srv/www/website_assets/movies:ro
    label:
      io.containers.autoupdate: image

# files
- name: create maw-files container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-files
    image: "docker.io/aerisg222/maw-files:latest"
    state: started
    volume:
      - "{{ maw_cert_volume.volume.Name }}:/certs:ro,z"
    label:
      io.containers.autoupdate: image

# photos
- name: create maw-photos container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-photos
    image: "docker.io/aerisg222/maw-photos:latest"
    state: started
    volume:
      - "{{ maw_cert_volume.volume.Name }}:/certs:ro,z"
    label:
      io.containers.autoupdate: image

# gateway
- name: create maw-gateway container
  containers.podman.podman_container:
    pod: "{{ mawus_podname }}"
    name: maw-gateway
    image: "docker.io/aerisg222/maw-gateway:latest"
    state: started
    security-opt:
      - label=disable
    volume:
      - "{{ maw_cert_volume.volume.Name }}:/certs:ro,z"
      - "{{ certbot_validation_volume.volume.Name }}:/var/www/certbot:ro,z"
      - "{{ certbot_certs_volume.volume.Name }}:/etc/letsencrypt:ro,z"
      - /srv/www/website_assets:/assets:ro
    label:
      io.containers.autoupdate: image
