- name: set role password
  containers.podman.podman_container:
    name: "{{ maw__env }}-maw-pginit-role-password"
    pod: "{{ maw__podman_pod }}"
    image: "{{ maw__podman_image_postgres }}"
    env_file: "{{ maw__podman_env_dir }}/maw-postgres.env"
    interactive: true
    state: started
    command:
      - psql
      - '-h'
      - 127.0.0.1
      - '-U'
      - postgres
      - '-d'
      - postgres
      - '-c'
      - "ALTER ROLE {{ item.username }} WITH PASSWORD '{{ item.password }}';"

- name: wait for set role container to stop
  ansible.builtin.include_role:
    name: podman_wait_for_stop
  vars:
    pod_stop__container_name: "{{ maw__env }}-maw-pginit-role-password"
    pod_stop__result_varname: role_pwd_result

- name: fail if password not set
  ansible.builtin.fail:
    msg: role passwords not properly set
  failed_when: role_pwd_result | int != 0
