---
- name: Make sure maw_env directory exists
  ansible.builtin.file:
    path: "{{ mawus_config.podman_env_dir }}"
    state: directory

- name: Make sure dataprotection dir exists for local site as it doesn't use managed volume
  ansible.builtin.file:
    path: "{{ mawus_config.dataprotection_dir }}"
    state: directory
  when: mawus_config.dataprotection_dir | length > 0

- name: Prepare environment files
  ansible.builtin.template:
    backup: true
    src: "maw_env/{{ item }}.j2"
    dest: "{{ mawus_config.podman_env_dir }}/{{ item }}"
    mode: u+rw
  loop:
    - maw-postgres.env
    - maw-api.env
    - maw-auth.env
    - maw-cache-sync.env
    - maw-reverse-geocode.env
    - maw-www.env

- name: Add env files to .bash_profile for dev
  ansible.builtin.blockinfile:
    path: "{{ mawus_config.bash_profile }}"
    block: |
      function load_dotenv(){
        # https://stackoverflow.com/a/66118031/134904
        source <(cat $1 | sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g")
      }

      set -o allexport

      [ -f "{{ mawus_config.podman_env_dir }}/maw-api.env" ] && load_dotenv "{{ mawus_config.podman_env_dir }}/maw-api.env"
      [ -f "{{ mawus_config.podman_env_dir }}/maw-auth.env" ] && load_dotenv "{{ mawus_config.podman_env_dir }}/maw-auth.env"
      [ -f "{{ mawus_config.podman_env_dir }}/maw-www.env" ] && load_dotenv "{{ mawus_config.podman_env_dir }}/maw-www.env"
      [ -f "{{ mawus_config.podman_env_dir }}/maw-cache-sync.env" ] && load_dotenv "{{ mawus_config.podman_env_dir }}/maw-cache-sync.env"

      set +o allexport
  when: mawus_config.env == 'dev'
