---
- name: Create user systemd directory if necessary
  ansible.builtin.file:
    path: "{{ home }}/.config/systemd/user"
    recurse: yes
    state: directory

- name: define common service and timers
  ansible.builtin.set_fact:
    services:
      - solr-indexer.service
    timers:
      - solr-indexer.timer
    services_prod:
      - certbot-renew.service
      - postgres-maintenance.service
      - remote-archive-daily.service
      - remote-archive-monthly.service
      - reverse-geocode.service
    timers_prod:
      - certbot-renew.timer
      - postgres-maintenance.timer
      - remote-archive-daily.timer
      - remote-archive-monthly.timer
      - reverse-geocode.timer

- name: Merge services and timers
  ansible.builtin.set_fact:
    services: "{{ services + services_prod }}"
    timers: "{{ timers + timers_prod }}"
  when: maw_env == 'prod'

- name: Prepare systemd service and timer files
  ansible.builtin.template:
    backup: yes
    src: "systemd/{{ item }}.j2"
    dest: "{{ home }}/.config/systemd/user/{{ item }}"
    mode: u+rw
  loop: "{{ services + timers }}"

- name: Enable timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
    daemon_reload: yes
  loop: "{{ timers }}"

- name: Configure Postgres Backups
  ansible.builtin.include_role:
    name: postgres_backup
  loop:
    - db_name: maw_website
      service_name: "{{ mawus_config.env }}-postgres-backup-mawus"
      systemd_dir: "{{ home }}/.config/systemd/user"
      pod_name: "{{ mawus_config.podman_podname }}"
      volume_name: "{{ postgres_backup_volume.volume.Name }}"
      env_file: "{{ mawus_config.podman_env_dir }}/maw-postgres.env"
      postgres_version: "{{ mawus_config.version_postgres }}"
      calendar: 01:00:00

    - db_name: idsrv
      service_name: "{{ mawus_config.env }}-postgres-backup-idsrv"
      systemd_dir: "{{ home }}/.config/systemd/user"
      pod_name: "{{ mawus_config.podman_podname }}"
      volume_name: "{{ postgres_backup_volume.volume.Name }}"
      env_file: "{{ mawus_config.podman_env_dir }}/maw-postgres.env"
      postgres_version: "{{ mawus_config.version_postgres }}"
      calendar: 01:05:00
