---
# ran into an issue where trying to create systemd unit files would not produce files and
# would stop all running containers.  it seems related to the following issue:
# https://github.com/containers/ansible-podman-collections/issues/368
# - name: Create systemd unit files
#   containers.podman.podman_pod:
#     name: "{{ mawus_podname }}"
#     generate_systemd:
#       new: yes
#       path: .config/systemd/user
#       container_prefix: ""
#       pod_prefix: ""
#       separator: ""

# hmm - this is stopping all containers too, but does produce all the unit files...
- name: Create systemd unit files (manually)
  ansible.builtin.command:
    cmd: "podman generate systemd -f -n --new {{ mawus_podname }}"
    chdir: .config/systemd/user

- name: Configure container order
  ansible.builtin.lineinfile:
    path: ".config/systemd/user/{{ item.unitfile }}"
    insertafter: ^After=.*$
    line: "Before={{ item.before }}"
  loop:
    - unitfile: container-maw-api.service
      before: container-maw-gateway.service
    - unitfile: container-maw-auth.service
      before: container-maw-gateway.service
    - unitfile: container-maw-files.service
      before: container-maw-gateway.service
    - unitfile: container-maw-photos.service
      before: container-maw-gateway.service
    - unitfile: container-maw-postgres.service
      before: container-maw-api.service container-maw-auth.service container-maw-www.service
    - unitfile: container-maw-redis.service
      before: container-maw-api.service container-maw-www.service
    - unitfile: container-maw-solr.service
      before: container-maw-api.service container-maw-www.service
    - unitfile: container-maw-www.service
      before: container-maw-gateway.service

- name: Enable mawus via systemd
  ansible.builtin.systemd:
    name: "pod-{{ mawus_podname }}"
    enabled: yes
    state: started
    scope: user
