---
- name: Configure Certbot Renew
  ansible.builtin.include_role:
    name: certbot_renew
  vars:
    cb__systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
    cb__service_name: "{{ mawus_config.env }}-certbot-renew"
    cb__start_job: false
    cb__enable_job: "{{ mawus_config.env == 'prod' }}"
    cb__calendar: '0/12:00:00'
    cb__pod: "{{ mawus_config.podman_podname }}"
    cb__container_image: "{{ mawus_config.podman_image_certbot }}"
    cb__validation_volume: "{{ certbot_validation_volume.volume.Name }}"
    cb__certs_volume: "{{ certbot_certs_volume.volume.Name }}"
  when: mawus_config.env == 'prod'

- name: Configure Reverse Geocoder
  ansible.builtin.include_role:
    name: reverse_geocoder
  vars:
    reverse_geocode_ctx:
      container_image: "{{ mawus_config.podman_image_reverse_geocode }}"
      service_name: "{{ mawus_config.env }}-reverse-geocoder"
      systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
      start_job: false
      enable_job: "{{ mawus_config.env == 'prod' }}"
      pod_name: "{{ mawus_config.podman_podname }}"
      volume_name: "{{ reverse_geocode_volume.volume.Name }}"
      env_file: "{{ mawus_config.podman_env_dir }}/maw-reverse-geocode.env"
      calendar: 00:45:00

- name: Configure Solr Indexer
  ansible.builtin.include_role:
    name: solr_indexer
  vars:
    solr_indexer_ctx:
      container_image: "{{ mawus_config.podman_image_solr_indexer }}"
      service_name: "{{ mawus_config.env }}-solr-indexer"
      systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
      start_job: false
      enable_job: "{{ mawus_config.env == 'prod' }}"
      pod_name: "{{ mawus_config.podman_podname }}"
      sql_username: "{{ mawus_config.sql_solr_username }}"
      sql_password: "{{ mawus_config.sql_solr_password }}"
      calendar: 00:50:00

- name: Configure Postgres Role Backup
  ansible.builtin.include_role:
    name: postgres_backup_roles
  vars:
    pg_backup_roles_ctx:
      container_image: "{{ mawus_config.podman_image_postgres }}"
      service_name: "{{ mawus_config.env }}-postgres-backup-roles"
      systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
      start_job: false
      enable_job: "{{ mawus_config.env == 'prod' }}"
      pod_name: "{{ mawus_config.podman_podname }}"
      volume_name: "{{ postgres_backup_volume.volume.Name }}"
      env_file: "{{ mawus_config.podman_env_dir }}/maw-postgres.env"
      postgres_version: "{{ mawus_config.version_postgres }}"
      calendar: 00:55:00

- name: Configure postgres backup for maw_website database
  ansible.builtin.include_role:
    name: postgres_backup_database
  vars:
    pg_bu_db__systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
    pg_bu_db__service: "{{ mawus_config.env }}-postgres-backup-mawus"
    pg_bu_db__pod: "{{ mawus_config.podman_podname }}"
    pg_bu_db__volume: "{{ postgres_backup_volume.volume.Name }}"
    pg_bu_db__envfile: "{{ mawus_config.podman_env_dir }}/maw-postgres.env"
    pg_bu_db__postgres_image: "{{ mawus_config.podman_image_postgres }}"
    pg_bu_db__db: maw_website
    pg_bu_db__calendar: '01:00:00'

- name: Configure postgres backup for idsrv database
  ansible.builtin.include_role:
    name: postgres_backup_database
  vars:
    pg_bu_db__systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
    pg_bu_db__service: "{{ mawus_config.env }}-postgres-backup-idsrv"
    pg_bu_db__pod: "{{ mawus_config.podman_podname }}"
    pg_bu_db__volume: "{{ postgres_backup_volume.volume.Name }}"
    pg_bu_db__envfile: "{{ mawus_config.podman_env_dir }}/maw-postgres.env"
    pg_bu_db__postgres_image: "{{ mawus_config.podman_image_postgres }}"
    pg_bu_db__db: idsrv
    pg_bu_db__calendar: '01:05:00'

- name: Configure Postgres Optimizations
  ansible.builtin.include_role:
    name: postgres_optimize
  loop_control:
    loop_var: pg_optimize_ctx
  loop:
    - db_name: maw_website
      container_image: "{{ mawus_config.podman_image_postgres }}"
      service_name: "{{ mawus_config.env }}-postgres-optimize-mawus"
      systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
      start_job: false
      enable_job: "{{ mawus_config.env == 'prod' }}"
      pod_name: "{{ mawus_config.podman_podname }}"
      env_file: "{{ mawus_config.podman_env_dir }}/maw-postgres.env"
      postgres_version: "{{ mawus_config.version_postgres }}"
      calendar: 01:10:00

    - db_name: idsrv
      container_image: "{{ mawus_config.podman_image_postgres }}"
      service_name: "{{ mawus_config.env }}-postgres-optimize-idsrv"
      systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
      start_job: false
      enable_job: "{{ mawus_config.env == 'prod' }}"
      pod_name: "{{ mawus_config.podman_podname }}"
      env_file: "{{ mawus_config.podman_env_dir }}/maw-postgres.env"
      postgres_version: "{{ mawus_config.version_postgres }}"
      calendar: 01:15:00

- name: Configure Postgres Backup Cleanup
  ansible.builtin.include_role:
    name: postgres_backup_cleanup
  vars:
    pg_clean__systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
    pg_clean__service: "{{ mawus_config.env }}-postgres-cleanup"
    pg_clean__postgres_image: "{{ mawus_config.podman_image_postgres }}"
    pg_clean__pod: "{{ mawus_config.podman_podname }}"
    pg_clean__volume: "{{ postgres_backup_volume.volume.Name }}"
    pg_clean__calendar: '01:20:00'

- name: Configure Postgres GDrive Daily Archive
  ansible.builtin.include_role:
    name: postgres_gdrive_archive
  vars:
    postgres_gdrive_archive_ctx:
      container_image: "{{ mawus_config.podman_image_gdrive }}"
      service_name: "{{ mawus_config.env }}-postgres-archive-daily"
      systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
      pod_name: "{{ mawus_config.podman_podname }}"
      files_to_archive_volume: "{{ postgres_backup_volume.volume.Name }}"
      creds_volume: "{{ gdrive_creds_volume.volume.Name }}"
      archive_folder: "{{ mawus_config.podman_podname }}-{{ ansible_host }}-pg_backup"
      retain_archive_duration: 10d
      calendar: 01:25:00

- name: Configure Postgres GDrive Monthly Archive
  ansible.builtin.include_role:
    name: postgres_gdrive_archive
  vars:
    postgres_gdrive_archive_ctx:
      container_image: "{{ mawus_config.podman_image_gdrive }}"
      service_name: "{{ mawus_config.env }}-postgres-archive-monthly"
      systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
      pod_name: "{{ mawus_config.podman_podname }}"
      files_to_archive_volume: "{{ postgres_backup_volume.volume.Name }}"
      creds_volume: "{{ gdrive_creds_volume.volume.Name }}"
      archive_folder: "{{ mawus_config.podman_podname }}-{{ ansible_host }}-pg_backup-monthly"
      retain_archive_duration: 2y
      calendar: '*-*-01 01:30:00'
