---
- name: copy certificate files from volume to server/host
  ansible.builtin.include_role:
    name: podman_copy
  vars:
    pod_cp__src_dir_or_volume: "{{ cert_vol }}"
    pod_cp__dest_dir_or_volume: "{{ remote_home_dir }}"
    pod_cp__command: "cp /src/{{ item }} /dest"
  loop:
    - api/api.pfx.pwd
    - auth/auth.pfx.pwd
    - www/www.pfx.pwd

- name: get api cert pwd
  ansible.builtin.slurp:
    src: "{{ remote_home_dir }}/api.pfx.pwd"
  register: api_pwd

- name: get auth cert pwd
  ansible.builtin.slurp:
    src: "{{ remote_home_dir }}/auth.pfx.pwd"
  register: auth_pwd

- name: get www cert pwd
  ansible.builtin.slurp:
    src: "{{ remote_home_dir }}/www.pfx.pwd"
  register: www_pwd

- name: set cert pwd variables
  ansible.builtin.set_fact:
    mawus__pfx_pwd_api: "{{ api_pwd.content | b64decode }}"
    mawus__pfx_pwd_auth: "{{ auth_pwd.content | b64decode }}"
    mawus__pfx_pwd_www: "{{ www_pwd.content | b64decode }}"

- name: delete temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ remote_home_dir }}/api.pfx.pwd"
    - "{{ remote_home_dir }}/auth.pfx.pwd"
    - "{{ remote_home_dir }}/www.pfx.pwd"

  when: mawus__certs_dir | length == 0
