- name: set role password
  containers.podman.podman_container:
    name: "{{ mawus_config.env }}-maw-pginit-role-password"
    pod: "{{ mawus_config.podman_podname }}"
    image: "docker.io/postgres:{{ mawus_config.version_postgres }}"
    env_file: "{{ mawus_config.podman_env_dir }}/maw-postgres.env"
    interactive: true
    state: started
    command:
      - psql
      - '-h'
      - 127.0.0.1
      - '-U'
      - postgres
      - '-d'
      - postgres
      - '-c'
      - "ALTER ROLE {{ item.username }} WITH PASSWORD '{{ item.password }}';"

- name: wait for set role container to stop
  ansible.builtin.include_tasks: wait_for_container_to_stop.yml
  vars:
    container_name: "{{ mawus_config.env }}-maw-pginit-role-password"
    exit_code_varname: role_pwd_result

- name: fail if password not set
  ansible.builtin.fail:
    msg: role passwords not properly set
  failed_when: role_pwd_result | int != 0
