---
- name: create maw cert volume
  containers.podman.podman_volume:
    name: "{{ maw__env }}-maw-certs"
    state: present
  when: maw__certs_dir | length == 0
  register: maw_cert_volume

- name: create maw-google-creds volume
  containers.podman.podman_volume:
    name: "{{ maw__env }}-maw-google-creds"
    state: present
  register: google_creds_volume

- name: create maw-gdrive-creds volume
  containers.podman.podman_volume:
    name: "{{ maw__env }}-maw-gdrive-creds"
    state: present
  register: gdrive_creds_volume

- name: create maw-certbot-validation volume
  containers.podman.podman_volume:
    name: "{{ maw__env }}-maw-certbot-validation"
    state: present
  when: maw__env == 'prod'
  register: certbot_validation_volume

- name: create maw-certbot-certs volume
  containers.podman.podman_volume:
    name: "{{ maw__env }}-maw-certbot-certs"
    state: present
  when: maw__env == 'prod'
  register: certbot_certs_volume
