---
- name: create maw-google-creds volume
  containers.podman.podman_volume:
    name: "{{ maw__env }}-maw-google-creds"
    state: present
  register: google_creds_volume

- name: create maw-gdrive-creds volume
  containers.podman.podman_volume:
    name: "{{ maw__env }}-maw-gdrive-creds"
    state: present
  register: gdrive_creds_volume
