---
- name: set the cert dir / volume name and fqdn prefix
  ansible.builtin.set_fact:
    cert_vol: "{{ (maw_cert_volume.volume is defined) | ternary(maw_cert_volume.volume.Name, mawus__certs_dir) }}"
    cert_fqdn_prefix: "{{ (mawus__env == 'prod') | ternary('', mawus__env) }}"

- name: ensure cert dir exists for local projects
  ansible.builtin.file:
    path: "{{ mawus__certs_dir }}"
    state: directory
    mode: u+rwx
  when: mawus__certs_dir | length > 0

# if you add a new environment, you may need to update the maw-certs image to be able to generate certs for the new env
# todo: add logic to maw-certs to dynamically accept new env name
- name: initialize internal certs
  containers.podman.podman_container:
    name: maw-certs
    image: "{{ mawus_config.podman_image_maw_certs }}"
    command: "{{ mawus__env }} {{ cert_fqdn_prefix }}"
    state: started
    interactive: true
    volume:
      - "{{ cert_vol }}:/maw-certs:rw,z"
  register: certs_container

- name: wait for cert initialization to complete
  ansible.builtin.include_tasks: wait_for_container_to_stop.yml
  vars:
    container_name: maw-certs
    exit_code_varname: certs_result

- name: fail if certs not created
  ansible.builtin.fail:
    msg: certs were not successfully created
  failed_when: certs_result | int != 0

- name: make system aware of self signed certificate authority
  block:

    # todo: evaluate dev (certs that are generated in managed volume) support
    - name: Add ca cert(s) to trusted sources
      become_user: root
      become: true
      ansible.builtin.copy:
        dest: "/usr/share/pki/ca-trust-source/anchors/maw_{{ mawus__env }}_{{ item | basename }}"
        src: "{{ item }}"
        mode: u+rw,go+r
      with_fileglob:
        - "{{ mawus__certs_dir }}/ca/ca_*.crt"

    - name: Make the system aware of the new ca certs
      become_user: root
      become: true
      ansible.builtin.command:
        cmd: update-ca-trust

    - name: load cert pwds into variables for subsequent steps
      ansible.builtin.set_fact:
        mawus_config_pfx_pwd_updates:
          pfx_pwd_api: "{{ lookup('file', remote_mawus_root + '/certs/api/api.pfx.pwd') }}"
          pfx_pwd_auth: "{{ lookup('file', remote_mawus_root + '/certs/auth/auth.pfx.pwd') }}"
          pfx_pwd_www: "{{ lookup('file', remote_mawus_root + '/certs/www/www.pfx.pwd') }}"

  when: mawus__certs_dir | length > 0
