---
- name: Configure Reverse Geocoder
  ansible.builtin.include_role:
    name: reverse_geocoder
  vars:
    maw_revgeo__systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
    maw_revgeo__service: "{{ maw__env }}-reverse-geocoder"
    maw_revgeo__pod: "{{ maw__podman_pod }}"
    maw_revgeo__volume: "{{ reverse_geocode_volume.volume.Name }}"
    maw_revgeo__envfile: "{{ maw__podman_env_dir }}/maw-reverse-geocode.env"
    maw_revgeo__image: "{{ maw__podman_image_reverse_geocode }}"
    maw_revgeo__calendar: '00:45:00'
