---
- name: copy certificate files from volume to server/host
  ansible.builtin.include_role:
    name: podman_copy_from_volume
  vars:
    volume_name: "{{ cert_vol }}"
    src_path: "{{ item }}"
    dest_relative_path: "{{ remote_home_dir }}"
  loop:
    - api/api.pfx.pwd
    - auth/auth.pfx.pwd
    - www/www.pfx.pwd

- name: get api cert pwd
  ansible.builtin.slurp:
    src: "{{ remote_home_dir }}/api.pfx.pwd"
  register: api_pwd

- name: get auth cert pwd
  ansible.builtin.slurp:
    src: "{{ remote_home_dir }}/auth.pfx.pwd"
  register: auth_pwd

- name: get www cert pwd
  ansible.builtin.slurp:
    src: "{{ remote_home_dir }}/www.pfx.pwd"
  register: www_pwd

- name: set cert pwd variables
  ansible.builtin.set_fact:
    mawus_config_pfx_pwd_updates:
      pfx_pwd_api: "{{ api_pwd.content | b64decode }}"
      pfx_pwd_auth: "{{ auth_pwd.content | b64decode }}"
      pfx_pwd_www: "{{ www_pwd.content | b64decode }}"

- name: delete temp files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ remote_home_dir }}/api.pfx.pwd"
    - "{{ remote_home_dir }}/auth.pfx.pwd"
    - "{{ remote_home_dir }}/www.pfx.pwd"

  when: mawus_config.certs_dir | length == 0

# todo: this does not work, apparently due to the scoping of mawus_config -
#       is there a way to update this variable so everything can live under mawus_config?
# - name: update mawus_config with pwd values did not work, so lets first set a temp var
#   ansible.builtin.set_fact:
#     mawus_config: "{{ mawus_config | combine(mawus_config_updates, recursive=True) }}"
