---
# todo: is this needed?
#- name: configure sysctl
#  become: yes
#  ansible.posix.sysctl:
#    name: net.ipv4.ip_forward
#    value: 1
#    state: present

- name: Enable masquerading
  become: yes
  ansible.posix.firewalld:
    masquerade: yes
    immediate: yes
    permanent: yes
    state: enabled
    zone: FedoraServer

- name: HTTP(S) Forwarding
  become: yes
  ansible.posix.firewalld:
    rich_rule: "rule family=ipv4 forward-port port={{ item.port }} protocol=tcp to-port={{ item.toport }}"
    immediate: yes
    permanent: yes
    state: enabled
    zone: FedoraServer
  loop:
    - port: 80
      toport: 8080
    - port: 443
      toport: 8443
