- name: wait for container to stop (rm should not be specified when starting container)
  containers.podman.podman_container_info:
    name: "{{ container_name }}"
  register: wait_container_info
  delay: 10
  retries: 24
  until: not wait_container_info.containers[0].State.Running

- name: set exit code variable
  ansible.builtin.set_fact:
    "{{ exit_code_varname }}": "{{ wait_container_info.containers[0].State.ExitCode }}"
  when: exit_code_varname is truthy

- name: finally, remove the dead container
  containers.podman.podman_container:
    name: "{{ container_name }}"
    state: absent
