- name: wait for container to exit
  containers.podman.podman_container_info:
    name: "{{ container_name }}"
  register: wait_container_info
  delay: 10
  retries: 24
  until: wait_container_info.containers | length == 0
