controller_home_dir: "{{ lookup('env', 'HOME') }}"
controller_mawus_root: "{{ controller_home_dir }}/ansible/apps/mikeandwan.us"
controller_mawus_env_root: "{{ controller_mawus_root }}/dev"
controller_secrets_file: "{{ controller_mawus_env_root }}/ansible/secret-vars.yml"

remote_home_dir: "{{ controller_home_dir }}"
remote_mawus_root: "{{ remote_home_dir }}/maw_dev"

# git root
git_root: "{{ controller_home_dir }}/git"

# asset directory root
asset_dir_root: /srv/www/website_assets

# mawus
maw__username: "{{ ansible_user_id }}"
maw__env: dev
maw__aspnet_env: development
maw__bash_profile: "{{ controller_home_dir }}/.bash_profile"
maw__allow_low_ports: false

maw__fqdn_naked: dev.mikeandwan.us
maw__fqdn_api: dev.api.mikeandwan.us
maw__fqdn_auth: dev.auth.mikeandwan.us
maw__fqdn_files: dev.files.mikeandwan.us
maw__fqdn_photos: dev.photos.mikeandwan.us
maw__fqdn_www: dev.www.mikeandwan.us

maw__pfx_api: "{{ remote_mawus_root }}/certs/api/api.pfx"
maw__pfx_auth: "{{ remote_mawus_root }}/certs/auth/auth.pfx"
maw__pfx_signing: "{{ remote_mawus_root }}/certs/signing/signing.pfx"
maw__pfx_www: "{{ remote_mawus_root }}/certs/www/www.pfx"

# to be set by cert process
maw__pfx_pwd_api:
maw__pfx_pwd_auth:
maw__pfx_pwd_www:

maw__gdrive_creds_dir:  # not needed for dev
maw__google_email_creds_dir: "{{ controller_mawus_env_root }}/google-creds"
maw__google_email_creds_file: "{{ controller_mawus_env_root }}/google-creds/www_emailer.json"
maw__google_creds_volume: "{{ maw__env }}-maw-google-creds"

maw__certs_dir: "{{ remote_mawus_root }}/certs"
maw__dataprotection_dir: "{{ remote_mawus_root }}/dataprotection"
maw__systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
maw__asset_dir_images: "{{ asset_dir_root }}/images"
maw__asset_dir_movies: "{{ asset_dir_root }}/movies"

maw__pg_backup_host_dir: "{{ controller_mawus_root }}/db_backups"
maw__pg_backup_roles: roles.sql
maw__pg_backup_idsrv: idsrv.20220307.dump
maw__pg_backup_www: maw_website.20220307.dump

maw__version_postgres: 14
maw__podman_image_postgres: docker.io/postgres:14-alpine

maw__podman_pod: dev-maw-pod
maw__podman_env_dir: "{{ remote_mawus_root }}/podman-env"
maw__podman_image_photos: ""
maw__podman_image_files: ""
maw__podman_image_gateway: ""
maw__podman_image_maw_certs: docker.io/aerisg222/maw-certs:latest
maw__podman_image_certbot: docker.io/certbot/certbot:latest
maw__podman_image_reverse_geocode: ""
maw__podman_image_gdrive: ""
maw__podman_publish_ports:
  - 8983:8983  # solr
  - 5432:5432  # postgres
  - 6379:6379  # redis

# postgres sql accounts for site
maw__sql_username: svc_www_maw
maw__sql_password: "{{ vault_password_sql_svc_www_maw }}"
maw__sql_postgres_password: "{{ vault_password_sql_postgres }}"
maw__sql_solr_username: svc_solr
maw__sql_solr_password: "{{ vault_password_sql_solr }}"

# google api key (maps / reverse geocode)
maw__google_api_key: "{{ vault_google_api_key }}"

# mawus redis settings
maw_redis__version: 6
maw_redis__pod: "{{ maw__podman_pod }}"
maw_redis__image: "docker.io/redis:{{ maw_redis__version }}-alpine"
maw_redis__container: "{{ maw__env }}-maw-redis"
maw_redis__volume: "{{ maw__env }}-maw-redis-{{ maw_redis__version }}"
maw_redis__cache_sync_image: docker.io/aerisg222/maw-cache-sync:latest
maw_redis__cache_sync_container: "{{ maw__env }}-maw-cache-sync"
maw_redis__cache_sync_envfile: "{{ maw__podman_env_dir }}/maw-cache-sync.env"
maw_redis__cache_sync_envfile_backup: false
maw_redis__cache_sync_sql_username: "{{ maw__sql_username }}"
maw_redis__cache_sync_sql_password: "{{ maw__sql_password }}"

# mawus solr settings
maw_solr__version: 8
maw_solr__systemd_dir: "{{ maw__systemd_dir }}"
maw_solr__tempdir: "{{ remote_home_dir }}/_tmp_ansible_maw_solr"
maw_solr__pod: "{{ maw__podman_pod }}"
maw_solr__image: "docker.io/solr:{{ maw_solr__version }}"
maw_solr__container: "{{ maw__env }}-maw-solr"
maw_solr__volume: "{{ maw__env }}-maw-solr-{{ maw__version_solr }}"
maw_solr__indexer_image: docker.io/aerisg222/maw-solr-indexer:latest
maw_solr__indexer_container: "{{ maw__env }}-solr-indexer"
maw_solr__indexer_sql_username: "{{ maw__sql_solr_username }}"
maw_solr__indexer_sql_password: "{{ maw__sql_solr_password }}"
maw_solr__indexer_calendar: '00:50:00'

# mawus api settings
mawus_api__pod: ""
mawus_api__image: ""
mawus_api__container: ""
mawus_api__cert_dir: "{{ maw__certs_dir }}"
mawus_api__cert_volume: ""
mawus_api__dataprotection_dir: "{{ remote_mawus_root }}/dataprotection/api"
mawus_api__dataprotection_volume: ""
mawus_api__dataprotection_volume_to_migrate: ""
mawus_api__envfile: "{{ maw__podman_env_dir }}/maw-api.env"
mawus_api__envfile_backup: false
mawus_api__aspnet_env: "{{ maw__aspnet_env }}"
mawus_api__pfx: "{{ maw__pfx_api }}"
mawus_api__pfx_pwd: ""
mawus_api__sql_username: "{{ maw__sql_username }}"
mawus_api__sql_password: "{{ maw__sql_password }}"
mawus_api__upload_dir: "{{ maw__upload_dir }}"
mawus_api__upload_volume: ""
mawus_api__upload_volume_to_migrate: ""
mawus_api__asset_dir_images: "{{ maw__asset_dir_images }}"

# mawus auth settings
mawus_auth__pod: ""
mawus_auth__image: ""
mawus_auth__container: ""
mawus_auth__cert_dir: "{{ maw__certs_dir }}"
mawus_auth__cert_volume: ""
mawus_auth__dataprotection_dir: "{{ remote_mawus_root }}/dataprotection/auth"
mawus_auth__dataprotection_volume: ""
mawus_auth__dataprotection_volume_to_migrate: ""
mawus_auth__envfile: "{{ maw__podman_env_dir }}/maw-auth.env"
mawus_auth__envfile_backup: false
mawus_auth__aspnet_env: "{{ maw__aspnet_env }}"
mawus_auth__google_creds_volume: ""
mawus_auth__google_email_creds_file:
mawus_auth__pfx: "{{ maw__pfx_auth }}"
mawus_auth__pfx_pwd:
mawus_auth__sql_username: "{{ maw__sql_username }}"
mawus_auth__sql_password: "{{ maw__sql_password }}"
mawus_auth__www_auth_client_secret: "{{ vault_www_auth_client_secret }}"
mawus_auth__google_plus_client_id: "{{ vault_google_plus_client_id }}"
mawus_auth__google_plus_client_secret: "{{ vault_google_plus_client_secret }}"
mawus_auth__twitter_client_id: "{{ vault_twitter_client_id }}"
mawus_auth__twitter_client_secret: "{{ vault_twitter_client_secret }}"
mawus_auth__microsoft_client_id: "{{ vault_microsoft_client_id }}"
mawus_auth__microsoft_client_secret: "{{ vault_microsoft_client_secret }}"
mawus_auth__github_client_id: "{{ vault_github_client_id }}"
mawus_auth__github_client_secret: "{{ vault_github_client_secret }}"
mawus_auth__pfx_signing: "{{ maw__pfx_signing }}"

# mawus www settings
mawus_www__pod: ""
mawus_www__image: ""
mawus_www__container: ""
mawus_www__cert_dir: "{{ maw__certs_dir }}"
mawus_www__cert_volume: ""
mawus_www__dataprotection_dir: "{{ remote_mawus_root }}/dataprotection/www"
mawus_www__dataprotection_volume: ""
mawus_www__dataprotection_volume_to_migrate: ""
mawus_www__envfile: "{{ maw__podman_env_dir }}/maw-www.env"
mawus_www__envfile_backup: false
mawus_www__pfx: "{{ maw__pfx_www }}"
mawus_www__pfx_pwd:
mawus_www__aspnet_env: "{{ maw__aspnet_env }}"
mawus_www__google_creds_volume: ""
mawus_www__google_email_creds_file: "{{ maw__google_email_creds_file }}"
mawus_www__sql_username: "{{ maw__sql_username }}"
mawus_www__sql_password: "{{ maw__sql_password }}"
mawus_www__auth_client_id: "{{ vault_www_auth_client_id }}"
mawus_www__auth_client_secret: "{{ vault_www_auth_client_secret }}"
mawus_www__google_recaptcha_site_key: "{{ vault_google_recaptcha_site_key }}"
mawus_www__google_recaptcha_secret_key: "{{ vault_google_recaptcha_secret_key }}"
mawus_www__asset_dir_images: "{{ maw__asset_dir_images }}"
mawus_www__asset_dir_movies: "{{ maw__asset_dir_movies }}"
