controller_home_dir: "{{ lookup('env', 'HOME') }}"
controller_mawus_root: "{{ controller_home_dir }}/ansible/apps/mikeandwan.us"
controller_mawus_env_root: "{{ controller_mawus_root }}/dev"
controller_secrets_file: "{{ controller_mawus_env_root }}/ansible/secret-vars.yml"

remote_home_dir: "{{ controller_home_dir }}"
remote_mawus_root: "{{ remote_home_dir }}/mawus_dev"

# git root
git_root: "{{ controller_home_dir }}/git"

# asset directory root
asset_dir_root: /srv/www/website_assets

# mawus
mawus__username: "{{ ansible_user_id }}"
mawus__env: dev
mawus__aspnet_env: development
mawus__bash_profile: "{{ controller_home_dir }}/.bash_profile"
mawus__allow_low_ports: false

mawus__fqdn_naked: dev.mikeandwan.us
mawus__fqdn_api: dev.api.mikeandwan.us
mawus__fqdn_auth: dev.auth.mikeandwan.us
mawus__fqdn_files: dev.files.mikeandwan.us
mawus__fqdn_photos: dev.photos.mikeandwan.us
mawus__fqdn_www: dev.www.mikeandwan.us

mawus__pfx_api: "{{ remote_mawus_root }}/certs/api/api.pfx"
mawus__pfx_auth: "{{ remote_mawus_root }}/certs/auth/auth.pfx"
mawus__pfx_signing: "{{ remote_mawus_root }}/certs/signing/signing.pfx"
mawus__pfx_www: "{{ remote_mawus_root }}/certs/www/www.pfx"

# to be set by cert process
mawus__pfx_pwd_api:
mawus__pfx_pwd_auth:
mawus__pfx_pwd_www:

mawus__gdrive_creds_dir:  # not needed for dev
mawus__google_email_creds_dir: "{{ controller_mawus_env_root }}/google-creds"
mawus__google_email_creds_file: "{{ controller_mawus_env_root }}/google-creds/www_emailer.json"

mawus__certs_dir: "{{ remote_mawus_root }}/certs"
mawus__dataprotection_dir: "{{ remote_mawus_root }}/dataprotection"
mawus__upload_dir: "{{ remote_mawus_root }}/maw-uploads"
mawus__systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
mawus__asset_dir_images: "{{ asset_dir_root }}/images"
mawus__asset_dir_movies: "{{ asset_dir_root }}/movies"

mawus__pg_backup_host_dir: "{{ controller_mawus_root }}/db_backups"
mawus__pg_backup_roles: roles.sql
mawus__pg_backup_idsrv: idsrv.20220307.dump
mawus__pg_backup_www: maw_website.20220307.dump

mawus__version_redis: 6
mawus__version_postgres: 14
mawus__version_solr: 8
mawus__podman_image_redis: docker.io/redis:6-alpine
mawus__podman_image_postgres: docker.io/postgres:14-alpine
mawus__podman_image_solr: docker.io/solr:8

mawus__podman_pod: dev-maw-pod
mawus__podman_env_dir: "{{ remote_mawus_root }}/podman-env"
mawus__podman_image_photos: ""
mawus__podman_image_files: ""
mawus__podman_image_auth: ""
mawus__podman_image_api: ""
mawus__podman_image_www: ""
mawus__podman_image_gateway: ""
mawus__podman_image_maw_certs: docker.io/aerisg222/maw-certs:latest
mawus__podman_image_certbot: docker.io/certbot/certbot:latest
mawus__podman_image_cache_sync: docker.io/aerisg222/maw-cache-sync:latest
mawus__podman_image_solr_indexer: docker.io/aerisg222/maw-solr-indexer:latest
mawus__podman_image_reverse_geocode: ""
mawus__podman_image_gdrive: ""
mawus__podman_publish_ports:
  - 8983:8983  # solr
  - 5432:5432  # postgres
  - 6379:6379  # redis

# postgres sql accounts for site
mawus__sql_username: svc_www_maw
mawus__sql_password: "{{ vault_password_sql_svc_www_maw }}"
mawus__sql_postgres_password: "{{ vault_password_sql_postgres }}"
mawus__sql_solr_username: svc_solr
mawus__sql_solr_password: "{{ vault_password_sql_solr }}"

# auth secrets
mawus__google_plus_client_id: "{{ vault_google_plus_client_id }}"
mawus__google_plus_client_secret: "{{ vault_google_plus_client_secret }}"
mawus__twitter_client_id: "{{ vault_twitter_client_id }}"
mawus__twitter_client_secret: "{{ vault_twitter_client_secret }}"
mawus__microsoft_client_id: "{{ vault_microsoft_client_id }}"
mawus__microsoft_client_secret: "{{ vault_microsoft_client_secret }}"
mawus__github_client_id: "{{ vault_github_client_id }}"
mawus__github_client_secret: "{{ vault_github_client_secret }}"
mawus__www_auth_client_secret: "{{ vault_www_auth_client_secret }}"
mawus__www_auth_client_id: "{{ vault_www_auth_client_id }}"

# google recaptcha key
mawus__google_recaptcha_site_key: "{{ vault_google_recaptcha_site_key }}"
mawus__google_recaptcha_secret_key: "{{ vault_google_recaptcha_secret_key }}"

# google api key (maps / reverse geocode)
mawus__google_api_key: "{{ vault_google_api_key }}"
