controller_home_dir: "{{ lookup('env', 'HOME') }}"
controller_mawus_root: "{{ controller_home_dir }}/ansible/apps/mikeandwan.us"
controller_mawus_env_root: "{{ controller_mawus_root }}/prod"
controller_secrets_file: "{{ controller_mawus_env_root }}/ansible/secret-vars.yml"

remote_home_dir: /home/svc_www_maw
remote_mawus_root: "{{ remote_home_dir }}/mawus"

# git root
git_root: "{{ controller_home_dir }}/git"

# asset directory root
asset_dir_root: /srv/www/website_assets

# mawus
mawus__username: svc_www_maw
mawus__password: "{{ vault_os_svc_www_maw }}"
mawus__env: prod
mawus__aspnet_env: production
mawus__bash_profile: # not needed for prod

mawus_config_prod:
  fqdn_naked: mikeandwan.us
  fqdn_api: api.mikeandwan.us
  fqdn_auth: auth.mikeandwan.us
  fqdn_files: files.mikeandwan.us
  fqdn_photos: photos.mikeandwan.us
  fqdn_www: www.mikeandwan.us

  pfx_api: /certs/api/api.pfx
  pfx_auth: /certs/auth/auth.pfx
  pfx_signing: /certs/signing/signing.pfx
  pfx_www: /certs/www/www.pfx

  gdrive_creds_dir: "{{ controller_mawus_env_root }}/gdrive-creds"
  google_email_creds_dir: "{{ controller_mawus_env_root }}/google-creds"
  google_email_creds_file: /google-creds/www_emailer.json

  allow_low_ports: true

  certs_dir: ""
  dataprotection_dir: ""
  upload_dir: ""

  systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
  asset_dir_images: "{{ asset_dir_root }}/images"
  asset_dir_movies: "{{ asset_dir_root }}/movies"

  pg_backup_host_dir: "{{ controller_mawus_root }}/db_backups"
  pg_backup_roles: roles.sql
  pg_backup_idsrv: idsrv.20220307.dump
  pg_backup_www: maw_website.20220307.dump

  # dependency versions
  version_redis: 6
  version_postgres: 14
  version_solr: 8

  podman_image_redis: docker.io/redis:6-alpine
  podman_image_postgres: docker.io/postgres:14-alpine
  podman_image_solr: docker.io/solr:8

  podman_podname: prod-maw-pod
  podman_env_dir: "{{ remote_mawus_root }}/podman-env"
  podman_image_photos: docker.io/aerisg222/maw-photos:latest
  podman_image_files: docker.io/aerisg222/maw-files:latest
  podman_image_auth: docker.io/aerisg222/maw-auth:latest
  podman_image_api: docker.io/aerisg222/maw-api:latest
  podman_image_www: docker.io/aerisg222/maw-www:latest
  podman_image_gateway: docker.io/aerisg222/maw-gateway:latest
  podman_image_maw_certs: docker.io/aerisg222/maw-certs:latest
  podman_image_certbot: docker.io/certbot/certbot:latest
  podman_image_cache_sync: docker.io/aerisg222/maw-cache-sync:latest
  podman_image_solr_indexer: docker.io/aerisg222/maw-solr-indexer:latest
  podman_image_reverse_geocode: docker.io/aerisg222/maw-reverse-geocode:latest
  podman_image_gdrive: docker.io/d0whc3r/gdrive:latest
  podman_publish_ports:
    - 80:80
    - 443:443

  # postgres sql accounts for site
  sql_username: svc_www_maw
  sql_password: "{{ vault_password_sql_svc_www_maw }}"
  sql_postgres_password: "{{ vault_password_sql_postgres }}"
  sql_solr_username: svc_solr
  sql_solr_password: "{{ vault_password_sql_solr }}"

  # auth secrets
  google_plus_client_id: "{{ vault_google_plus_client_id }}"
  google_plus_client_secret: "{{ vault_google_plus_client_secret }}"
  twitter_client_id: "{{ vault_twitter_client_id }}"
  twitter_client_secret: "{{ vault_twitter_client_secret }}"
  microsoft_client_id: "{{ vault_microsoft_client_id }}"
  microsoft_client_secret: "{{ vault_microsoft_client_secret }}"
  github_client_id: "{{ vault_github_client_id }}"
  github_client_secret: "{{ vault_github_client_secret }}"
  www_auth_client_secret: "{{ vault_www_auth_client_secret }}"
  www_auth_client_id: "{{ vault_www_auth_client_id }}"

  # google recaptcha key
  google_recaptcha_site_key: "{{ vault_google_recaptcha_site_key }}"
  google_recaptcha_secret_key: "{{ vault_google_recaptcha_secret_key }}"

  # google api key (maps / reverse geocode)
  google_api_key: "{{ vault_google_api_key }}"
