# test home
home: "{{ lookup('env', 'HOME') }}"

# asset directory root
asset_dir_root: /srv/www/website_assets

# where to store supporting files outside project / site
external_root: "{{ home }}/ansible/apps/mikeandwan.us"
external_site_dir: "{{ external_root }}/test"
external_vars_file: "{{ external_site_dir }}/ansible/secret-vars.yml"

mawus_config_test:
  env: test
  aspnet_env: test

  # os level account that will run the site
  service_account:
    username: "{{ ansible_user_id }}"
    subuid: 100000-165535
    subgid: 100000-165535
    enable_linger: no

  bash_profile: "{{ home }}/.bash_profile"

  fqdn_naked: test.mikeandwan.us
  fqdn_api: test.api.mikeandwan.us
  fqdn_auth: test.auth.mikeandwan.us
  fqdn_files: test.files.mikeandwan.us
  fqdn_photos: test.photos.mikeandwan.us
  fqdn_www: test.www.mikeandwan.us

  pfx_api: "/certs/api/api.pfx"
  pfx_auth: "/certs/auth/auth.pfx"
  pfx_signing: "/certs/signing/signing.pfx"
  pfx_www: "/certs/www/www.pfx"

  allow_low_ports: no
  port_api: 5001
  port_auth: 5011
  port_photos: 4200
  port_files: 4300
  port_www: 5021

  # certs written to dir to simplify adding ca cert to host
  certs_dir: "{{ external_site_dir }}/certs"
  dataprotection_dir: ""
  upload_dir: ""

  systemd_dir: "{{ home }}/.config/systemd/user"
  asset_dir_images: "{{ asset_dir_root }}/images"
  asset_dir_movies: "{{ asset_dir_root }}/movies"

  pg_backup_host_dir: "{{ external_root }}/db_backups"
  pg_backup_roles: "roles.sql"
  pg_backup_idsrv: "idsrv.20220307.dump"
  pg_backup_www: "maw_website.20220307.dump"

  # dependency versions
  version_redis: 6
  version_postgres: 14
  version_solr: 8

  podman_podname: test-maw-pod
  podman_env_dir: "{{ external_site_dir }}/podman-env"
  podman_image_photos: "localhost/maw-photos-test"
  podman_image_files: "localhost/maw-files-test"
  podman_image_auth: "localhost/maw-auth-test"
  podman_image_api: "localhost/maw-api-test"
  podman_image_www: "localhost/maw-www-test"
  podman_image_gateway: ""
  podman_image_cache_sync: "docker.io/aerisg222/maw-cache-sync:latest"
  podman_publish_ports:
    - 5001:5001
    - 5011:5011
    - 5021:5021

  gateway_volumes:
    #- "{{ maw_cert_volume.volume.Name }}:/maw-certs:ro,z"
    #- "{{ asset_dir_root }}:/assets:ro"
    #- "{{ certbot_validation_volume.volume.Name }}:/var/www/certbot:ro,z"
    #- "{{ certbot_certs_volume.volume.Name }}:/etc/letsencrypt:ro,z"

  # postgres sql accounts for site
  sql_username: svc_www_maw
  sql_password: "{{ vault_password_sql_svc_www_maw }}"
  sql_postgres_password: "{{ vault_password_sql_postgres }}"
  sql_solr_username: svc_solr
  sql_solr_password: "{{ vault_password_sql_solr }}"

  # auth secrets
  google_plus_client_id: "{{ vault_google_plus_client_id }}"
  google_plus_client_secret: "{{ vault_google_plus_client_secret }}"
  twitter_client_id: "{{ vault_twitter_client_id }}"
  twitter_client_secret: "{{ vault_twitter_client_secret }}"
  microsoft_client_id: "{{ vault_microsoft_client_id }}"
  microsoft_client_secret: "{{ vault_microsoft_client_secret }}"
  github_client_id: "{{ vault_github_client_id }}"
  github_client_secret: "{{ vault_github_client_secret }}"
  www_auth_client_secret: "{{ vault_www_auth_client_secret }}"
  www_auth_client_id: "{{ vault_www_auth_client_id }}"

  # google recaptcha key
  google_recaptcha_site_key: "{{ vault_google_recaptcha_site_key }}"
  google_recaptcha_secret_key: "{{ vault_google_recaptcha_secret_key }}"

  # google api key (maps / reverse geocode)
  google_api_key: "{{ vault_google_api_key }}"

  # google email creds
  google_email_creds_dir: ""
  google_email_creds_file: "{{ external_site_dir }}/google-creds/www_emailer.json"
