controller_home_dir: "{{ lookup('env', 'HOME') }}"
controller_mawus_root: "{{ controller_home_dir }}/ansible/apps/mikeandwan.us"
controller_mawus_env_root: "{{ controller_mawus_root }}/test"
controller_secrets_file: "{{ controller_mawus_env_root }}/ansible/secret-vars.yml"

remote_home_dir: "{{ controller_home_dir }}"
remote_mawus_root: "{{ remote_home_dir }}/mawus_test"

# asset directory root
asset_dir_root: /srv/www/website_assets

# mawus
mawus__username: "{{ ansible_user_id }}"
mawus__env: test
mawus__aspnet_env: test
mawus__bash_profile: "{{ controller_home_dir }}/.bash_profile"

mawus__fqdn_naked: test.mikeandwan.us
mawus__fqdn_api: test.api.mikeandwan.us
mawus__fqdn_auth: test.auth.mikeandwan.us
mawus__fqdn_files: test.files.mikeandwan.us
mawus__fqdn_photos: test.photos.mikeandwan.us
mawus__fqdn_www: test.www.mikeandwan.us

mawus__pfx_api: /certs/api/api.pfx
mawus__pfx_auth: /certs/auth/auth.pfx
mawus__pfx_signing: /certs/signing/signing.pfx
mawus__pfx_www: /certs/www/www.pfx

mawus__gdrive_creds_dir:  # not needed for test
mawus__google_email_creds_dir: "{{ controller_mawus_env_root }}/google-creds"
mawus__google_email_creds_file: /google-creds/www_emailer.json


mawus_config_test:
  allow_low_ports: false

  # certs written to dir to simplify adding ca cert to host
  certs_dir: "{{ remote_mawus_root }}/certs"
  dataprotection_dir: ""
  upload_dir: ""

  systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
  asset_dir_images: "{{ asset_dir_root }}/images"
  asset_dir_movies: "{{ asset_dir_root }}/movies"

  pg_backup_host_dir: "{{ controller_mawus_root }}/db_backups"
  pg_backup_roles: roles.sql
  pg_backup_idsrv: idsrv.20220307.dump
  pg_backup_www: maw_website.20220307.dump

  # dependency versions
  version_redis: 6
  version_postgres: 14
  version_solr: 8

  podman_image_redis: docker.io/redis:6-alpine
  podman_image_postgres: docker.io/postgres:14-alpine
  podman_image_solr: docker.io/solr:8

  podman_podname: test-maw-pod
  podman_env_dir: "{{ remote_mawus_root }}/podman-env"
  podman_image_photos: localhost/maw-photos-test
  podman_image_files: localhost/maw-files-test
  podman_image_auth: localhost/maw-auth-test
  podman_image_api: localhost/maw-api-test
  podman_image_www: localhost/maw-www-test
  podman_image_gateway: localhost/maw-gateway-test
  podman_image_maw_certs: docker.io/aerisg222/maw-certs:latest
  podman_image_certbot: ""
  podman_image_cache_sync: docker.io/aerisg222/maw-cache-sync:latest
  podman_image_solr_indexer: docker.io/aerisg222/maw-solr-indexer:latest
  podman_image_reverse_geocode: docker.io/aerisg222/maw-reverse-geocode:latest
  podman_image_gdrive: ""
  podman_publish_ports:
    - 8080:8080
    - 8443:8443

  # postgres sql accounts for site
  sql_username: svc_www_maw
  sql_password: "{{ vault_password_sql_svc_www_maw }}"
  sql_postgres_password: "{{ vault_password_sql_postgres }}"
  sql_solr_username: svc_solr
  sql_solr_password: "{{ vault_password_sql_solr }}"

  # auth secrets
  google_plus_client_id: "{{ vault_google_plus_client_id }}"
  google_plus_client_secret: "{{ vault_google_plus_client_secret }}"
  twitter_client_id: "{{ vault_twitter_client_id }}"
  twitter_client_secret: "{{ vault_twitter_client_secret }}"
  microsoft_client_id: "{{ vault_microsoft_client_id }}"
  microsoft_client_secret: "{{ vault_microsoft_client_secret }}"
  github_client_id: "{{ vault_github_client_id }}"
  github_client_secret: "{{ vault_github_client_secret }}"
  www_auth_client_secret: "{{ vault_www_auth_client_secret }}"
  www_auth_client_id: "{{ vault_www_auth_client_id }}"

  # google recaptcha key
  google_recaptcha_site_key: "{{ vault_google_recaptcha_site_key }}"
  google_recaptcha_secret_key: "{{ vault_google_recaptcha_secret_key }}"

  # google api key (maps / reverse geocode)
  google_api_key: "{{ vault_google_api_key }}"
