controller_home_dir: "{{ lookup('env', 'HOME') }}"
controller_mawus_root: "{{ controller_home_dir }}/ansible/apps/mikeandwan.us"
controller_mawus_env_root: "{{ controller_mawus_root }}/prod"
controller_secrets_file: "{{ controller_mawus_env_root }}/ansible/secret-vars.yml"

remote_home_dir: /home/svc_www_maw
remote_mawus_root: "{{ remote_home_dir }}/mawus"

# git root
git_root: "{{ controller_home_dir }}/git"

# asset directory root
asset_dir_root: /srv/www/website_assets

# mawus
mawus__username: svc_www_maw
mawus__password: "{{ vault_os_svc_www_maw }}"
mawus__env: prod
mawus__aspnet_env: production
mawus__bash_profile: # not needed for prod
mawus__allow_low_ports: true

mawus__fqdn_naked: mikeandwan.us
mawus__fqdn_api: api.mikeandwan.us
mawus__fqdn_auth: auth.mikeandwan.us
mawus__fqdn_files: files.mikeandwan.us
mawus__fqdn_photos: photos.mikeandwan.us
mawus__fqdn_www: www.mikeandwan.us

mawus__pfx_api: /certs/api/api.pfx
mawus__pfx_auth: /certs/auth/auth.pfx
mawus__pfx_signing: /certs/signing/signing.pfx
mawus__pfx_www: /certs/www/www.pfx

# to be set by cert process
mawus__pfx_pwd_api:
mawus__pfx_pwd_auth:
mawus__pfx_pwd_www:

mawus__gdrive_creds_dir: "{{ controller_mawus_env_root }}/gdrive-creds"
mawus__google_email_creds_dir: "{{ controller_mawus_env_root }}/google-creds"
mawus__google_email_creds_file: /google-creds/www_emailer.json

mawus__certs_dir: ""
mawus__dataprotection_dir: ""
mawus__upload_dir: ""
mawus__systemd_dir: "{{ remote_home_dir }}/.config/systemd/user"
mawus__asset_dir_images: "{{ asset_dir_root }}/images"
mawus__asset_dir_movies: "{{ asset_dir_root }}/movies"

mawus__pg_backup_host_dir: "{{ controller_mawus_root }}/db_backups"
mawus__pg_backup_roles: roles.sql
mawus__pg_backup_idsrv: idsrv.20220307.dump
mawus__pg_backup_www: maw_website.20220307.dump

mawus__version_redis: 6
mawus__version_postgres: 14
mawus__version_solr: 8

mawus__podman_image_redis: docker.io/redis:6-alpine
mawus__podman_image_postgres: docker.io/postgres:14-alpine
mawus__podman_image_solr: docker.io/solr:8

mawus__podman_pod: prod-maw-pod
mawus__podman_env_dir: "{{ remote_mawus_root }}/podman-env"
mawus__podman_image_photos: docker.io/aerisg222/maw-photos:latest
mawus__podman_image_files: docker.io/aerisg222/maw-files:latest
mawus__podman_image_auth: docker.io/aerisg222/maw-auth:latest
mawus__podman_image_api: docker.io/aerisg222/maw-api:latest
mawus__podman_image_www: docker.io/aerisg222/maw-www:latest
mawus__podman_image_gateway: docker.io/aerisg222/maw-gateway:latest
mawus__podman_image_maw_certs: docker.io/aerisg222/maw-certs:latest
mawus__podman_image_certbot: docker.io/certbot/certbot:latest
mawus__podman_image_cache_sync: docker.io/aerisg222/maw-cache-sync:latest
mawus__podman_image_solr_indexer: docker.io/aerisg222/maw-solr-indexer:latest
mawus__podman_image_reverse_geocode: docker.io/aerisg222/maw-reverse-geocode:latest
mawus__podman_image_gdrive: docker.io/d0whc3r/gdrive:latest
mawus__podman_publish_ports:
  - 80:80
  - 443:443

# postgres sql accounts for site
mawus__sql_username: svc_www_maw
mawus__sql_password: "{{ vault_password_sql_svc_www_maw }}"
mawus__sql_postgres_password: "{{ vault_password_sql_postgres }}"
mawus__sql_solr_username: svc_solr
mawus__sql_solr_password: "{{ vault_password_sql_solr }}"

# auth secrets
mawus__google_plus_client_id: "{{ vault_google_plus_client_id }}"
mawus__google_plus_client_secret: "{{ vault_google_plus_client_secret }}"
mawus__twitter_client_id: "{{ vault_twitter_client_id }}"
mawus__twitter_client_secret: "{{ vault_twitter_client_secret }}"
mawus__microsoft_client_id: "{{ vault_microsoft_client_id }}"
mawus__microsoft_client_secret: "{{ vault_microsoft_client_secret }}"
mawus__github_client_id: "{{ vault_github_client_id }}"
mawus__github_client_secret: "{{ vault_github_client_secret }}"
mawus__www_auth_client_secret: "{{ vault_www_auth_client_secret }}"
mawus__www_auth_client_id: "{{ vault_www_auth_client_id }}"

# google recaptcha key
mawus__google_recaptcha_site_key: "{{ vault_google_recaptcha_site_key }}"
mawus__google_recaptcha_secret_key: "{{ vault_google_recaptcha_secret_key }}"

# google api key (maps / reverse geocode)
mawus__google_api_key: "{{ vault_google_api_key }}"
