# dev home
home: "{{ lookup('env', 'HOME') }}"

# git root
git_root: "{{ home }}/git"

# asset directory root
asset_dir_root: /srv/www/website_assets

# where to store supporting files outside project / site
external_root: "{{ home }}/ansible/apps/mikeandwan.us"
external_site_dir: "{{ external_root }}/dev"
external_vars_file: "{{ external_site_dir }}/ansible/secret-vars.yml"

mawus_config_dev:
  env: dev
  aspnet_env: development

  # os level account that will run the site
  service_account:
    username: "{{ ansible_user_id }}"
    subuid: 100000-165535
    subgid: 100000-165535
    enable_linger: no

  bash_profile: "{{ home }}/.bash_profile"

  fqdn_naked: dev.mikeandwan.us
  fqdn_api: dev.api.mikeandwan.us
  fqdn_auth: dev.auth.mikeandwan.us
  fqdn_files: dev.files.mikeandwan.us
  fqdn_photos: dev.photos.mikeandwan.us
  fqdn_www: dev.www.mikeandwan.us

  pfx_api: "{{ external_site_dir }}/certs/api/api.pfx"
  pfx_auth: "{{ external_site_dir }}/certs/auth/auth.pfx"
  pfx_signing: "{{ external_site_dir }}/certs/signing/signing.pfx"
  pfx_www: "{{ external_site_dir }}/certs/www/www.pfx"

  allow_low_ports: no
  port_api: 5001
  port_auth: 5011
  port_photos: 4200
  port_files: 4300
  port_www: 5021

  certs_dir: "{{ external_site_dir }}/certs"
  dataprotection_dir: "{{ external_site_dir }}/dataprotection"
  upload_dir: "{{ external_site_dir }}/maw-uploads"

  systemd_dir: "{{ home }}/.config/systemd/user"
  asset_dir_images: "{{ asset_dir_root }}/images"
  asset_dir_movies: "{{ asset_dir_root }}/movies"

  pg_backup_host_dir: "{{ external_root }}/db_backups"
  pg_backup_roles: "roles.sql"
  pg_backup_idsrv: "idsrv.20220307.dump"
  pg_backup_www: "maw_website.20220307.dump"

  # dependency versions
  version_redis: 6
  version_postgres: 14
  version_solr: 8

  podman_podname: dev-maw-pod
  podman_env_dir: "{{ external_site_dir }}/podman-env"
  podman_image_photos: ""
  podman_image_files: ""
  podman_image_auth: ""
  podman_image_api: ""
  podman_image_www: ""
  podman_image_gateway: ""
  podman_image_cache_sync: "docker.io/aerisg222/maw-cache-sync:latest"
  podman_publish_ports:
    - 8983:8983  # solr
    - 5432:5432  # postgres
    - 6379:6379  # redis
    #- 80:80
    #- 443:443

  gateway_volumes:
    #- "{{ maw_cert_volume.volume.Name }}:/maw-certs:ro,z"
    #- "{{ asset_dir_root }}:/assets:ro"
    #- "{{ certbot_validation_volume.volume.Name }}:/var/www/certbot:ro,z"
    #- "{{ certbot_certs_volume.volume.Name }}:/etc/letsencrypt:ro,z"

  # postgres sql accounts for site
  sql_username: svc_www_maw
  sql_password: "{{ vault_password_sql_svc_www_maw }}"
  sql_postgres_password: "{{ vault_password_sql_postgres }}"
  sql_solr_username: svc_solr
  sql_solr_password: "{{ vault_password_sql_solr }}"

  # auth secrets
  google_plus_client_id: "{{ vault_google_plus_client_id }}"
  google_plus_client_secret: "{{ vault_google_plus_client_secret }}"
  twitter_client_id: "{{ vault_twitter_client_id }}"
  twitter_client_secret: "{{ vault_twitter_client_secret }}"
  microsoft_client_id: "{{ vault_microsoft_client_id }}"
  microsoft_client_secret: "{{ vault_microsoft_client_secret }}"
  github_client_id: "{{ vault_github_client_id }}"
  github_client_secret: "{{ vault_github_client_secret }}"
  www_auth_client_secret: "{{ vault_www_auth_client_secret }}"
  www_auth_client_id: "{{ vault_www_auth_client_id }}"

  # google recaptcha key
  google_recaptcha_site_key: "{{ vault_google_recaptcha_site_key }}"
  google_recaptcha_secret_key: "{{ vault_google_recaptcha_secret_key }}"

  # google api key (maps / reverse geocode)
  google_api_key: "{{ vault_google_api_key }}"

  # google email creds
  google_email_creds_dir: "{{ external_site_dir }}/google-creds"
  google_email_creds_file: "{{ external_site_dir }}/google-creds/www_emailer.json"
