---
- name: Create user systemd directory if necessary
  ansible.builtin.file:
    path: "{{ systemd_dir }}"
    recurse: yes
    state: directory

- name: "Create systemd service file for {{ db_name }} database backup job"
  ansible.builtin.template:
    src: postgres_backup.service.j2
    dest: "{{ systemd_dir }}/{{ service_name }}.service"
    mode: u+rw

- name: "Create systemd timer file for {{ db_name }} database backup job"
  ansible.builtin.template:
    src: postgres_backup.timer.j2
    dest: "{{ systemd_dir }}/{{ service_name }}.timer"
    mode: u+rw

- name: Enable job timer
  ansible.builtin.systemd:
    name: "{{ service_name }}.timer"
    enabled: yes
    state: started
    scope: user
    daemon_reload: yes
