---
- name: Set facts for systemd_job role
  ansible.builtin.set_fact:
    sysd_job__service_template: "{{ role_path }}/templates/solr-indexer.service.j2"
    sysd_job__timer_template: "{{ role_path }}/templates/solr-indexer.timer.j2"
    sysd_job__systemd_dir: "{{ solr_indexer_ctx.systemd_dir }}"
    sysd_job__service: "{{ solr_indexer_ctx.service_name }}"

- name: Configure systemd job to reindex the solr database
  ansible.builtin.include_role:
    name: systemd_job
