---
- name: Allow firewall traffic
  become: true
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    service: "{{ item }}"
    state: enabled
    zone: FedoraServer
  loop: "{{ fw__allowed_services }}"

- name: Deny firewall traffic
  become: true
  ansible.posix.firewalld:
    immediate: true
    permanent: true
    service: "{{ item }}"
    state: disabled
    zone: FedoraServer
  loop: "{{ fw__denied_services }}"
