---
- name: Set facts for systemd_job role
  ansible.builtin.set_fact:
    service_template: "{{ role_path }}/templates/reverse-geocode.service.j2"
    timer_template: "{{ role_path }}/templates/reverse-geocode.timer.j2"

- name: Configure systemd job to run the reverse geocoder
  ansible.builtin.include_role:
    name: systemd_job
  vars:
    systemd_job_ctx:
      systemd_dir: "{{ reverse_geocode_ctx.systemd_dir }}"
      service_name: "{{ reverse_geocode_ctx.service_name }}"
      start_job: "{{ reverse_geocode_ctx.start_job }}"
      enable_job: "{{ reverse_geocode_ctx.enable_job }}"
      service_template: "{{ service_template }}"
      timer_template: "{{ timer_template }}"
