---
- name: Set facts for systemd_job role
  ansible.builtin.set_fact:
    sysd_job__service_template: "{{ role_path }}/templates/reverse-geocode.service.j2"
    sysd_job__timer_template: "{{ role_path }}/templates/reverse-geocode.timer.j2"
    sysd_job__systemd_dir: "{{ rev_geo__systemd_dir }}"
    sysd_job__service: "{{ rev_geo__service }}"

- name: Configure systemd job to run the reverse geocoder
  ansible.builtin.include_role:
    name: systemd_job
