---
argument_specs:
  main:
    short_description: This role is responsible for getting google creds from production and saving them to the control server
    options:
      maw_prod_google_creds_bu__hostname:
        type: str
        required: true
        description: Name of the server where the current production site is running

      maw_prod_google_creds_bu__username:
        type: str
        required: true
        description: Name of the user running the application in the production environment

      maw_prod_google_creds_bu__use_existing_backups:
        type: str
        required: true
        description: Specifies if this process should be skipped if backups already exist on the control node

      maw_prod_google_creds_bu__volume:
        type: str
        required: true
        description: Name of the current production volume containing the google credentials

      maw_prod_google_creds_bu__control_dir:
        type: str
        required: true
        description: Absolute path to the google backup directory on the controller

      maw_prod_google_creds_bu__temp_remote_dir:
        type: str
        required: true
        description: Absolute path to the temp google backup directory on the production server
