---
- name: Set facts for systemd_job role
  ansible.builtin.set_fact:
    service_template: "{{ role_path }}/templates/postgres_backup_roles.service.j2"
    timer_template: "{{ role_path }}/templates/postgres_backup_roles.timer.j2"

- name: Configure systemd job for postgres role backup
  ansible.builtin.include_role:
    name: systemd_job
  vars:
    systemd_job_ctx:
      systemd_dir: "{{ pg_backup_roles_ctx.systemd_dir }}"
      service_name: "{{ pg_backup_roles_ctx.service_name }}"
      start_job: "{{ pg_backup_roles_ctx.start_job }}"
      enable_job: "{{ pg_backup_roles_ctx.enable_job }}"
      service_template: "{{ service_template }}"
      timer_template: "{{ timer_template }}"