---
argument_specs:
  main:
    short_description: Creates solr objects for mikeandwan.us
    options:
      maw_solr__version:
        type: int
        required: true
        description: Major version number of Solr

      maw_solr__systemd_dir:
        type: str
        required: true
        description: The user systemd dir where service and timer files will be written

      maw_solr__tempdir:
        type: str
        required: true
        description: A path to a temp directory that can be used.  This should be a subdirectory of a user's homedir.

      maw_solr__pod:
        type: str
        required: true
        description: Then name of the pod in which to run Solr

      maw_solr__image:
        type: str
        required: true
        description: Fully qualified image name for solr

      maw_solr__container:
        type: str
        required: true
        description: The name to give to the container running solr

      maw_solr__volume:
        type: str
        required: true
        description: The podman volume where solr configuration and index data will be stored
