---
- name: Install Android Studio Dependencies
  become: yes
  ansible.builtin.dnf:
    state: present
    name:
      - zlib.i686
      - ncurses-libs.i686
      - bzip2-libs.i686

- name: Install VM acceleration dependencies for Android Emulator
  become: yes
  ansible.builtin.dnf:
    state: present
    name:
      - bridge-utils
      - libvirt
      - virt-install
      - qemu-kvm

- name: Start and Enable libvirtd
  become: yes
  ansible.builtin.service:
    state: started
    enabled: yes
    name: libvirtd

# You may need to enable VT-D or VT-x or SVM in your bios - you should see that /dev/kvm exists
# Android Studio requires accepting Terms and Conditions - so not automating this now
