---
- name: Add Azure CLI Repo
  become: true
  ansible.builtin.yum_repository:
    name: azure_cli
    description: Azure CLI
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  notify: update_package_cache

- name: Install Azure CLI
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - azure-cli
