---
- name: Set hostname
  when: hostname | length > 0 and domain | length > 0
  become: yes
  hostname:
    name: '{{ hostname }}.{{ domain }}'
    use: systemd

- name: Add VSCode Repo
  become: yes
  yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Teams Repo
  become: yes
  yum_repository:
    name: teams
    description: MS Teams repo
    baseurl: https://packages.microsoft.com/yumrepos/ms-teams
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Google Chrome repo
  become: yes
  yum_repository:
    name: google-chrome
    description: Google Chrome repo
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add Google Earth repo
  become: yes
  yum_repository:
    name: google-earth
    description: Google Earth repo
    baseurl: https://dl.google.com/linux/earth/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Add RPM Fusion repos
  become: yes
  dnf:
    disable_gpg_check: yes
    state: present
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Add NVIDIA Container Repos
  become: yes
  when: has_nvidia_gpu
  uri:
    url: https://nvidia.github.io/nvidia-container-runtime/rhel8.3/nvidia-container-runtime.repo
    dest: /etc/yum.repos.d/nvidia-container-runtime.repo
    creates: /etc/yum.repos.d/nvidia-container-runtime.repo

- name: Update Package Metadata and Packages
  become: yes
  dnf:
    update_cache: yes
    state: present

- name: Install Nvidia Drivers
  become: yes
  when: has_nvidia_gpu
  dnf:
    state: present
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda

- name: Install Packages
  become: yes
  dnf:
    state: present
    name:
      - blender
      - buildah
      - code
      - dnf-plugin-system-upgrade
      - dotnet
      - ffmpeg
      - fira-code-fonts
      - gimp
      - gnome-extensions-app
      - gnome-tweaks
      - gnucash
      - google-chrome-stable
      - google-earth-pro-stable
      - google-roboto-fonts
      - htop
      - ImageMagick-devel
      - inkscape
      - jpegoptim
      - keepassxc
      - libjpeg-turbo-utils
      - libva-utils
      - libva-vdpau-driver
      - nodejs
      - nvidia-container-runtime
      - perl-Image-ExifTool
      - podman
      - postgresql-server
      - postgresql-upgrade
      - python3-ansible-lint
      - rawtherapee
      - teams
      - tmux
      - vdpauinfo

#    - name: update network name

#    - name: Setup SSH Key (create / add to remotes?)

#    - name: Setup local PSQL (restores)
