---
- name: Import android_studio.yml
  ansible.builtin.import_tasks: android_studio.yml
  when: fed_w__android_studio

- name: Import aws_cli.yml
  ansible.builtin.import_tasks: aws_cli.yml
  when: fed_w__aws_cli

- name: Import azure_cli.yml
  ansible.builtin.import_tasks: azure_cli.yml
  when: fed_w__azure_cli

- name: Import azure_data_studio.yml
  ansible.builtin.import_tasks: azure_data_studio.yml
  when: fed_w__azure_data_studio

- name: Import google_chrome.yml
  ansible.builtin.import_tasks: google_chrome.yml
  when: fed_w__google_chrome

- name: Import google_earth.yml
  ansible.builtin.import_tasks: google_earth.yml
  when: fed_w__google_earth

- name: Import ms_teams.yml
  ansible.builtin.import_tasks: ms_teams.yml
  when: fed_w__ms_teams

- name: Import nvidia.yml
  ansible.builtin.import_tasks: nvidia.yml
  when: fed_w__nvidia

- name: Import powershell.yml
  ansible.builtin.import_tasks: powershell.yml
  when: fed_w__powershell

- name: Import vscode.yml
  ansible.builtin.import_tasks: vscode.yml
  when: fed_w__vscode

- name: Add RPM Fusion repos
  become: true
  ansible.builtin.dnf:
    disable_gpg_check: true
    state: present
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Install Packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - blender
      - buildah
      - dotnet
      - ffmpeg
      - fira-code-fonts
      - gimp
      - gnome-extensions-app
      - gnome-tweaks
      - gnucash
      - google-roboto-fonts
      - htop
      - ImageMagick-devel
      - inkscape
      - jpegoptim
      - keepassxc
      - libjpeg-turbo-utils
      - libva-utils
      - libva-vdpau-driver
      - nodejs
      - perl-Image-ExifTool
      - podman
      - postgresql
      - python3-ansible-lint
      - rawtherapee
      - tmux
      - vdpauinfo
      - vlc

- name: Install piper
  become: true
  ansible.builtin.dnf:
    state: present
    name: piper
  when: fed_w__piper

- name: configure sysctl for workstations
  become: true
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - key: "fs.inotify.max_user_instances"
      value: "1024"
