---
- name: Import android_studio.yml
  ansible.builtin.import_tasks: android_studio.yml
  when: android_studio

- name: Import aws_cli.yml
  ansible.builtin.import_tasks: aws_cli.yml
  when: aws_cli

- name: Import azure_cli.yml
  ansible.builtin.import_tasks: azure_cli.yml
  when: azure_cli

- name: Import azure_data_studio.yml
  ansible.builtin.import_tasks: azure_data_studio.yml
  when: azure_data_studio

- name: Import google_chrome.yml
  ansible.builtin.import_tasks: google_chrome.yml
  when: google_chrome

- name: Import google_earth.yml
  ansible.builtin.import_tasks: google_earth.yml
  when: google_earth

- name: Import ms_teams.yml
  ansible.builtin.import_tasks: ms_teams.yml
  when: ms_teams

- name: Import nvidia.yml
  ansible.builtin.import_tasks: nvidia.yml
  when: nvidia

- name: Import powershell.yml
  ansible.builtin.import_tasks: powershell.yml
  when: powershell

- name: Import vscode.yml
  ansible.builtin.import_tasks: vscode.yml
  when: vscode

- name: Add RPM Fusion repos
  become: true
  dnf:
    disable_gpg_check: true
    state: present
    name:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Install Packages
  become: true
  dnf:
    state: present
    name:
      - blender
      - buildah
      - dotnet
      - ffmpeg
      - fira-code-fonts
      - gimp
      - gnome-extensions-app
      - gnome-tweaks
      - gnucash
      - google-roboto-fonts
      - htop
      - ImageMagick-devel
      - inkscape
      - jpegoptim
      - keepassxc
      - libjpeg-turbo-utils
      - libva-utils
      - libva-vdpau-driver
      - nodejs
      - perl-Image-ExifTool
      - podman
      - python3-ansible-lint
      - rawtherapee
      - tmux
      - vdpauinfo
      - vlc

- name: Install piper
  become: true
  dnf:
    state: present
    name: piper
  when: piper

- name: configure sysctl for workstations
  become: true
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { key: "fs.inotify.max_user_instances", value: "1024" }
