---
- name: Add VSCode Repo
  become: true
  ansible.builtin.yum_repository:
    name: vscode
    description: Visual Studio Code repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  notify: update_package_cache

- name: Install Visual Studio Code
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - code
