---
- name: delete current backup directory on controller
  ansible.builtin.file:
    path: "{{ maw_prod_pg_bu__control_dir }}"
    state: absent
  delegate_to: localhost

- name: make sure remote temp directory does not exist
  ansible.builtin.file:
    path: "{{ maw_prod_pg_bu__temp_remote_dir }}"
    state: absent
    mode: u+rwx

- name: ensure remote temp directory exists
  ansible.builtin.file:
    path: "{{ maw_prod_pg_bu__temp_remote_dir }}"
    state: directory
    mode: u+rwx

- name: backup roles to temp directory
  containers.podman.podman_container:
    pod: "{{ maw_prod_pg_bu__pod }}"
    image: "{{ maw_prod_pg_bu__image }}"
    name: "{{ maw_prod_pg_bu__container }}"
    env_file: "{{ maw_prod_pg_bu__envfile }}"
    interactive: true
    volume:
      - "{{ maw_prod_pg_bu__temp_remote_dir }}:/pg_backup:rw,z"
    command:
      - pg_dumpall
      - '-h'
      - localhost
      - '-U'
      - postgres
      - '--roles-only'
      - '--no-role-passwords'
      - '--file'
      - '/pg_backup/roles.sql'

- name: wait for role backup to complete
  ansible.builtin.include_role:
    name: podman_wait_for_stop
  vars:
    pod_stop__container_name: "{{ maw_prod_pg_bu__container }}"
    pod_stop__result_varname: _maw_prod_pg_bu__result

- name: fail if role backup failed
  ansible.builtin.fail:
    msg: roles were not successfully backed up
  failed_when: _maw_prod_pg_bu__result | int != 0

- name: backup idsrv to temp directory
  containers.podman.podman_container:
    pod: "{{ maw_prod_pg_bu__pod }}"
    image: "{{ maw_prod_pg_bu__image }}"
    name: "{{ maw_prod_pg_bu__container }}"
    env_file: "{{ maw_prod_pg_bu__envfile }}"
    interactive: true
    volume:
      - "{{ maw_prod_pg_bu__temp_remote_dir }}:/pg_backup:rw,z"
    command:
      - pg_dump
      - '-h'
      - localhost
      - '-U'
      - postgres
      - '-Fc'
      - idsrv
      - '--file'
      - '/pg_backup/idsrv.dump'

- name: wait for idsrv backup to complete
  ansible.builtin.include_role:
    name: podman_wait_for_stop
  vars:
    pod_stop__container_name: "{{ maw_prod_pg_bu__container }}"
    pod_stop__result_varname: _maw_prod_pg_bu__result

- name: fail if idsrv backup failed
  ansible.builtin.fail:
    msg: idsrv database was not successfully backed up
  failed_when: _maw_prod_pg_bu__result | int != 0

- name: backup maw_website to temp directory
  containers.podman.podman_container:
    pod: "{{ maw_prod_pg_bu__pod }}"
    image: "{{ maw_prod_pg_bu__image }}"
    name: "{{ maw_prod_pg_bu__container }}"
    env_file: "{{ maw_prod_pg_bu__envfile }}"
    interactive: true
    volume:
      - "{{ maw_prod_pg_bu__temp_remote_dir }}:/pg_backup:rw,z"
    command:
      - pg_dump
      - '-h'
      - localhost
      - '-U'
      - postgres
      - '-Fc'
      - maw_website
      - '--file'
      - '/pg_backup/maw_website.dump'

- name: wait for maw_website backup to complete
  ansible.builtin.include_role:
    name: podman_wait_for_stop
  vars:
    pod_stop__container_name: "{{ maw_prod_pg_bu__container }}"
    pod_stop__result_varname: _maw_prod_pg_bu__result

- name: fail if maw_website backup failed
  ansible.builtin.fail:
    msg: maw_website database was not successfully backed up
  failed_when: _maw_prod_pg_bu__result | int != 0

- name: copy backup directory to controller
  ansible.builtin.fetch:
    dest: "{{ maw_prod_pg_bu__control_dir }}"
    src: "{{ _maw_prod_pg_bu__file }}"
  loop_control:
    loop_var: _maw_prod_pg_bu__file
  loop:
    - "{{ maw_prod_pg_bu__temp_remote_dir }}/roles.sql"
    - "{{ maw_prod_pg_bu__temp_remote_dir }}/idsrv.dump"
    - "{{ maw_prod_pg_bu__temp_remote_dir }}/maw_website.dump"

- name: finally, delete remote temp directory
  ansible.builtin.file:
    path: "{{ maw_prod_pg_bu__temp_remote_dir }}"
    state: absent

- name: move files on controller to the root backup dir
  ansible.builtin.command:
    cmd: "mv {{ item }} {{ maw_prod_pg_bu__control_dir }}"
  delegate_to: localhost
  with_fileglob:
        - "{{ maw_prod_pg_bu__control_dir }}/{{ maw_prod_pg_bu__hostname }}{{ maw_prod_pg_bu__temp_remote_dir }}/*"

- name: delete local backup dir
  ansible.builtin.file:
    path: "{{ maw_prod_pg_bu__control_dir }}/{{ maw_prod_pg_bu__hostname }}"
    state: absent
  delegate_to: localhost
