---
- name: Set facts for systemd_job role
  ansible.builtin.set_fact:
    sysd_job__service_template: "{{ role_path }}/templates/postgres_backup_database.service.j2"
    sysd_job__timer_template: "{{ role_path }}/templates/postgres_backup_database.timer.j2"
    sysd_job__systemd_dir: "{{ pg_bu_db__systemd_dir }}"
    sysd_job__service: "{{ pg_bu_db__service }}"

- name: Configure systemd job for database backup
  ansible.builtin.include_role:
    name: systemd_job
