---
argument_specs:
  main:
    short_description: Role to configure a systemd service and timer to run the solr indexer process
    options:
      maw_solridx__systemd_dir:
        type: str
        required: true
        description: the directory where to write the systemd service and timer files

      maw_solridx__service:
        type: str
        required: true
        description: the name of the service

      maw_solridx__pod:
        type: str
        required: true
        description: the name of the pod in which to run the reverse geocode service

      maw_solridx__image:
        type: str
        required: true
        description: the name of docker image for the reverse geocode process

      maw_solridx__container:
        type: str
        required: true
        description: the name to use for the running container

      maw_solridx__sql_username:
        type: str
        required: true
        description: the username to use when connecting to the maw_website postgres database

      maw_solridx__sql_password:
        type: str
        required: true
        description: the password to use when connecting to the maw_website postgres database

      maw_solridx__calendar:
        type: str
        required: true
        description: the systemd calendar specification to define when this job runs
