---
- name: pull solr image
  containers.podman.podman_image:
    name: "{{ maw_solr__image }}"

- name: create solr volume
  containers.podman.podman_volume:
    name: "{{ maw_solr__volume }}"
    state: present

- name: maw-solr container
  containers.podman.podman_container:
    name: "{{ maw_solr__container }}"
    pod: "{{ maw_solr__pod }}"
    image: "{{ maw_solr__image }}"
    state: started
    volume:
      - "{{ maw_solr__volume }}:/var/solr:rw,z"
    label:
      io.containers.autoupdate: image

- name: wait for solr container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ maw_solr__container }}"

- name: include configure_solr.yml
  ansible.builtin.include_tasks: configure_solr.yml

- name: Configure Solr Indexer
  ansible.builtin.include_role:
    name: maw_solr_indexer

- name: run indexer
  ansible.builtin.systemd:
    name: "{{ maw_solr__indexer_container }}"
    enabled: false
    state: started
    scope: user
