---
- name: pull image
  containers.podman.podman_image:
    name: "{{ maw_photos__image }}"

- name: maw-photos container
  containers.podman.podman_container:
    name: "{{ maw_photos__container }}"
    pod: "{{ maw_photos__pod }}"
    image: "{{ maw_photos__image }}"
    state: started
    volume:
      - "{{ maw_photos__cert_volume }}:/certs:ro,z"
    label:
      io.containers.autoupdate: image

- name: wait for photos container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ maw_photos__container }}"
