---
- name: configure photos container
  ansible.builtin.include_tasks:
    file: container_hosted.yml
  when: maw_photos__run_in_container

# currently nothing else to do if it is 'native hosted' / doesn't run in container
