---
- name: pull www image
  containers.podman.podman_image:
    name: "{{ mawus_www__image }}"

- name: create www dataprotection volume
  containers.podman.podman_volume:
    name: "{{ mawus_www__dataprotection_volume }}"
    state: present
  register: _mawus_www__dataprotection_volume_result

- name: migrate www dataprotection files from original volume
  ansible.builtin.include_role:
    name: podman_copy
  when: >
    _mawus_www__dataprotection_volume_result.changed
    and
    mawus_www__dataprotection_volume_to_migrate | length > 0
  vars:
    pod_cp__skip_if_src_not_exists: true
    pod_cp__src_dir_or_volume: "{{ mawus_www__dataprotection_volume_to_migrate }}"
    pod_cp__dest_dir_or_volume: "{{ mawus_www__dataprotection_volume }}"

- name: maw-www container
  containers.podman.podman_container:
    name: "{{ mawus_www__container }}"
    pod: "{{ mawus_www__pod }}"
    image: "{{ mawus_www__image }}"
    state: started
    env_file: "{{ mawus_www__envfile }}/"
    security_opt:
      - label=disable
    volume:
      - "{{ mawus_www__cert_volume }}:/certs:ro,z"
      - "{{ mawus_www__dataprotection_volume }}:/dataprotection:rw,Z"
      - "{{ mawus_www__google_creds_volume }}:/google-creds:ro,z"
      - "{{ mawus_www__asset_dir_images }}:/srv/www/website_assets/images:ro"
      - "{{ mawus_www__asset_dir_movies }}:/srv/www/website_assets/movies:ro"
    label:
      io.containers.autoupdate: image

- name: wait for www container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ mawus_www__container }}"
