---
- name: prepare www environment file
  ansible.builtin.include_role:
    name: maw_envfile
  vars:
    maw_env__template: maw-www.env.j2
    maw_env__path: "{{ maw_www__envfile }}"
    maw_env__backup: "{{ maw_www__envfile_backup }}"

- name: configure natively hosted www site
  ansible.builtin.include_tasks:
    file: native_hosted.yml
  when: not maw_www__run_in_container

- name: configure container hosted www site
  ansible.builtin.include_tasks:
    file: container_hosted.yml
  when: maw_www__run_in_container
