---
- name: Add Service Accounts
  become: true
  ansible.builtin.user:
    name: "{{ maw_host__username }}"
    password: "{{ maw_host__password | password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: Initialize podman
  ansible.builtin.include_role:
    name: podman_init
  vars:
    pod_init__linger_users:
      - "{{ maw_host__username }}"

- name: Include maw_hostnames.yml
  ansible.builtin.include_tasks: maw_hostnames.yml
  loop_control:
    loop_var: _maw_host__hostname
  loop: "{{ maw_host__hostnames }}"

# https://github.com/containers/podman/blob/main/rootless.md
- name: permit rootless users to listen on low ports
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: 80
    state: present
  when: maw_host__allow_low_ports

- name: Configure firewall
  ansible.builtin.include_role:
    name: firewall
  vars:
    fw__allowed_services: "{{ maw_host__allow_firewall_services }}"

- name: Initialize host directories
  ansible.builtin.include_tasks: maw_host_directories.yml

# todo: copy files to server

- name: Include maw_admin_scripts
  ansible.builtin.include_role:
    name: maw_admin_scripts
  when: maw_host__deploy_admin_scripts
