---
argument_specs:
  main:
    short_description: Creates api service and supporting objects for mikeandwan.us
    options:
      maw_api__run_in_container:
        type: bool
        required: true
        description: Indicates if maw_api should run in a container (we will run this manually for dev)

      maw_api__pod:
        type: str
        required: true
        description: Name of the pod in which the api container should run

      maw_api__image:
        type: str
        required: true
        description: Fully qualified api image to use

      maw_api__container:
        type: str
        required: true
        description: Name of the container

      maw_api__cert_dir:
        type: str
        required: true
        description: Local directory where the certificates are stored

      maw_api__cert_volume:
        type: str
        required: true
        description: Name of the volume where certificates are stored

      maw_api__dataprotection_dir:
        type: str
        required: true
        description: Full path to directory where dataprotection files will be written

      maw_api__dataprotection_volume:
        type: str
        required: true
        description: Name of the volume where data protection files are stored

      maw_api__envfile:
        type: str
        required: true
        description: Path to the api environment file

      maw_api__envfile_backup:
        type: bool
        required: true
        description: Indicates if the existing envfile should be backed up before being overwritten

      maw_api__aspnet_env:
        type: str
        required: true
        description: Specifies the environment for the aspnet application

      maw_api__pfx:
        type: str
        required: true
        description: Path to the api pfx file

      maw_api__pfx_pwd:
        type: str
        required: true
        description: The password for the api pfx

      maw_api__sql_username:
        type: str
        required: true
        description: The name of the user to connect to postgres

      maw_api__sql_password:
        type: str
        required: true
        description: The password for the postgres user

      maw_api__upload_dir:
        type: str
        required: true
        description: The path to the uploads directory

      maw_api__upload_volume:
        type: str
        required: true
        description: The name of the uploads volume

      maw_api__asset_dir_images:
        type: str
        required: true
        description: Absolute path to the photos / images asset directory

      maw_api__dataprotection_controller_backup_dir:
        type: str
        required: true
        description: Absolute path to the directory on the controller that holds the api dataprotection backup

      maw_api__restore_dataprotection:
        type: bool
        required: true
        description: Indicates if the dataprotection volume should be restored from backup

      maw_api__temp_dir:
        type: str
        required: true
        description: Absolute path to a temp directory on the remote

      maw_api__upload_controller_backup_dir:
        type: str
        required: true
        description: Absolute path to the directory on the controller that holds the uploads backup
