---
- name: ensure we have latest images for mikeandwan.us
  containers.podman.podman_image:
    name: "{{ maw_gateway__image }}"

- name: define common volumes for gateway
  ansible.builtin.set_fact:
    _maw_gateway__volumes:
      - "{{ maw_gateway__cert_volume }}:/certs:ro,z"
      - "{{ maw_gateway__asset_dir }}:/assets:ro"

- name: certbot related tasks
  block:
    - name: create maw-certbot-certs volume
      containers.podman.podman_volume:
        name: "{{ maw_gateway__certbot_certs_volume }}"
        state: present
      register: _maw_gateway__certbot_certs_volume

    - name: create maw-certbot-validation volume
      containers.podman.podman_volume:
        name: "{{ maw_gateway__certbot_validation_volume }}"
        state: present
      register: _maw_gateway__certbot_validation_volume

    - name: migrate certbot certs
      ansible.builtin.include_role:
        name: podman_copy
      when: _maw_gateway__certbot_certs_volume.changed
      vars:
        pod_cp__skip_if_src_not_exists: true
        pod_cp__src_dir_or_volume: "{{ maw_gateway__certbot_certs_volume_to_migrate }}"
        pod_cp__dest_dir_or_volume: "{{ maw_gateway__certbot_certs_volume }}"
        pod_cp__command: cp -R /src/internal/. /dest

    - name: migrate certbot validation
      ansible.builtin.include_role:
        name: podman_copy
      when: _maw_gateway__certbot_validation_volume.changed
      vars:
        pod_cp__skip_if_src_not_exists: true
        pod_cp__src_dir_or_volume: "{{ maw_gateway__certbot_validation_volume_to_migrate }}"
        pod_cp__dest_dir_or_volume: "{{ maw_gateway__certbot_validation_volume }}"

    - name: define prod only volumes for gateway (letsencrypt)
      ansible.builtin.set_fact:
        _maw_gateway__volumes_prod:
          - "{{ maw_gateway__certbot_validation_volume }}:/var/www/certbot:ro,z"
          - "{{ maw_gateway__certbot_certs_volume }}:/etc/letsencrypt:ro,z"

    - name: merge all volumes needed for gateway
      ansible.builtin.set_fact:
        _maw_gateway__volumes: "{{ _maw_gateway__volumes + _maw_gateway__volumes_prod }}"
  when: maw_gateway__certbot_certs_volume | length > 0

- name: maw-gateway container
  containers.podman.podman_container:
    name: "{{ maw_gateway__container }}"
    pod: "{{ maw_gateway__pod }}"
    image: "{{ maw_gateway__image }}"
    state: started
    volume: "{{ _maw_gateway__volumes }}"
    security_opt:
      - label=disable
    label:
      io.containers.autoupdate: image

- name: wait for gateway container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ maw_gateway__container }}"
