---
- name: configure gateway container
  ansible.builtin.include_tasks:
    file: container_hosted.yml
  when: maw_gateway__run_in_container

# currently nothing else to do if it is 'native hosted' / doesn't run in container
