---
argument_specs:
  main:
    short_description: Role to restore a pg database if it does not already exist
    options:
      pg_res_db__db:
        type: str
        required: true
        description: name of the database to restore

      pg_res_db__pod:
        type: str
        required: true
        description: name of the pod in which to run the restore container

      pg_res_db__image:
        type: str
        required: true
        description: name of the docker image to use

      pg_res_db__container:
        type: str
        default: pg-restore
        description: name of the container to use when running different steps of the restore

      pg_res_db__envfile:
        type: str
        required: true
        description: path to the postgres environment file

      pg_res_db__backup_file:
        type: str
        required: true
        description: the path to the backup file to restore for this database
