---
- name: get postgres backup
  ansible.builtin.include_role:
    name: maw_prod_postgres_backup

- name: get google credentials backup
  ansible.builtin.include_role:
    name: maw_prod_google_creds_backup

- name: get gdrive credentials backup
  ansible.builtin.include_role:
    name: maw_prod_gdrive_creds_backup

- name: get uploads backup
  ansible.builtin.include_role:
    name: maw_prod_uploads_backup
  when: maw__do_uploads_backup
