---
# - name: Prepare self signed / internal certs
#   ansible.builtin.include_role:
#     name: maw_certs

- name: Initialize maw_pod
  ansible.builtin.include_role:
    name: maw_pod
  vars:
    maw_pod__mode: setup

- name: Setup postgres container
  ansible.builtin.include_role:
    name: maw_postgres


# - name: Finalize maw_pod as a systemd service
#   ansible.builtin.include_role:
#     name: maw_pod
#   vars:
#     maw_pod__mode: systemd
