---
# - name: Prepare self signed / internal certs
#   ansible.builtin.include_role:
#     name: maw_certs

# - name: Initialize maw_pod
#   ansible.builtin.include_role:
#     name: maw_pod
#   vars:
#     maw_pod__mode: setup

# - name: Setup shared google creds volume
#   ansible.builtin.include_role:
#     name: maw_google_credentials

# - name: Setup postgres container
#   ansible.builtin.include_role:
#     name: maw_postgres

# - name: Configure redis
#   ansible.builtin.include_role:
#     name: maw_redis

- name: Configure solr
  ansible.builtin.include_role:
    name: maw_solr

- name: Configure Solr Indexer
  ansible.builtin.include_role:
    name: maw_solr_indexer

# REMINDER: our current db needs a couple scripts applied for the indexer to succeed.  make sure to run
#           the 014 and 015 scripts if this fails, and then try again.
- name: Run Solr Indexer
  ansible.builtin.systemd:
    name: "{{ maw_solridx__service }}"
    enabled: false
    state: started
    scope: user

# - name: Finalize maw_pod as a systemd service
#   ansible.builtin.include_role:
#     name: maw_pod
#   vars:
#     maw_pod__mode: systemd
