---
argument_specs:
  main:
    short_description: Creates redis server and supporting objects for mikeandwan.us
    options:
      maw_gateway__pod:
        type: str
        required: true
        description: The name of the pod in which to run the container

      maw_gateway__image:
        type: str
        required: true
        description: The full name of the docker image

      maw_gateway__container:
        type: str
        required: true
        description: The name to use for the running container

      maw_gateway__cert_volume:
        type: str
        required: true
        description: The volume where internal certificates are stored

      maw_gateway__certbot_certs_volume:
        type: str
        required: true
        description: The volume where certbot can store Let's Encrypt certificates

      maw_gateway__certbot_certs_volume_to_migrate:
        type: str
        required: true
        description: The original name of the certbot volume containing existing Let's Encrypt certificates

      maw_gateway__certbot_validation_volume:
        type: str
        required: true
        description: The volume used with certbot to validate domain ownership

      maw_gateway__certbot_validation_volume_to_migrate:
        type: str
        required: true
        description: The original name of the certbot validation volume to migrate to the new volume

      maw_gateway__asset_dir:
        type: str
        required: true
        description: The path to the root asset directory on the host
