---
argument_specs:
  main:
    short_description: Role to configure a systemd service and timer to run postgres optimization tasks
    options:
      pg_optimize__systemd_dir:
        type: str
        required: true
        description: the directory where to write the systemd service and timer files

      pg_optimize__service:
        type: str
        required: true
        description: the name of the service

      pg_optimize__pod:
        type: str
        required: true
        description: the name of the pod to run this container in

      pg_optimize__envfile:
        type: str
        required: true
        description: the path to the environment file containing the postgres user password

      pg_optimize__postgres_image:
        type: str
        required: true
        description: the name of the postgres docker image

      pg_optimize__db:
        type: str
        required: true
        description: the name of the database to optimize

      pg_optimize__calendar:
        type: str
        required: true
        description: the systemd calendar specification to define when this job runs
