---
- name: Set facts for systemd_job role
  ansible.builtin.set_fact:
    sysd_job__service_template: "{{ role_path }}/templates/certbot-renew.service.j2"
    sysd_job__timer_template: "{{ role_path }}/templates/certbot-renew.timer.j2"
    sysd_job__systemd_dir: "{{ cb__systemd_dir }}"
    sysd_job__service: "{{ cb__service_name }}"

- name: Configure systemd job to run the certbot renew job
  ansible.builtin.include_role:
    name: systemd_job
