---
- name: "wait for container {{ container_name }} to start"
  containers.podman.podman_container_info:
    name: "{{ pod_start__container_name }}"
  register: _pod_start__container_info
  delay: 10
  retries: 12
  until: _pod_start__container_info.containers[0].State.Running
