---
- name: pull images
  containers.podman.podman_image:
    name: "{{ _mawus_redis__item }}"
  loop_control:
    loop_var: _mawus_redis__item
  loop:
    - "{{ mawus_redis__image }}"
    - "{{ mawus_redis__cache_sync_image }}"

- name: create redis volume
  containers.podman.podman_volume:
    name: "{{ mawus_redis__volume }}"
    state: present

- name: redis container
  containers.podman.podman_container:
    name: "{{ mawus_redis__name }}"
    pod: "{{ mawus__podman_pod }}"
    image: "{{ mawus_redis__image }}"
    command: redis-server --save 60 1
    state: started
    volume:
      - "{{ mawus_redis__volume }}:/data:rw,z"
    label:
      io.containers.autoupdate: image

- name: wait for redis container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ mawus_redis__name }}"

- name: prepare cache sync environment file
  ansible.builtin.include_role:
    name: mawus_envfile
  vars:
    mawus_env__template: maw-cache-sync.env.j2
    mawus_env__path: "{{ mawus_redis__cache_sync_envfile }}"
    mawus_env__backup: "{{ mawus__env == 'prod' }}"

- name: maw-cache-sync container
  containers.podman.podman_container:
    name: "{{ mawus_redis__cache_sync_name }}"
    pod: "{{ mawus__podman_pod }}"
    image: "{{ mawus_redis__cache_sync_image }}"
    env_file: "{{ mawus_redis__cache_sync_envfile }}"
    state: started
    label:
      io.containers.autoupdate: image

- name: wait for maw-cache-sync container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ mawus_redis__cache_sync_name }}"
