---
- name: pull images
  containers.podman.podman_image:
    name: "{{ _maw_redis__item }}"
  loop_control:
    loop_var: _maw_redis__item
  loop:
    - "{{ maw_redis__image }}"
    - "{{ maw_redis__cache_sync_image }}"

- name: create redis volume
  containers.podman.podman_volume:
    name: "{{ maw_redis__volume }}"
    state: present

- name: redis container
  containers.podman.podman_container:
    name: "{{ maw_redis__container }}"
    pod: "{{ maw_redis__pod }}"
    image: "{{ maw_redis__image }}"
    command: redis-server --save 60 1
    state: started
    volume:
      - "{{ maw_redis__volume }}:/data:rw,z"
    label:
      io.containers.autoupdate: image

- name: wait for redis container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ maw_redis__container }}"

- name: prepare cache sync environment file
  ansible.builtin.include_role:
    name: maw_envfile
  vars:
    mawus_env__template: maw-cache-sync.env.j2
    mawus_env__path: "{{ maw_redis__cache_sync_envfile }}"
    mawus_env__backup: "{{ maw_redis__cache_sync_envfile_backup }}"

- name: maw-cache-sync container
  containers.podman.podman_container:
    name: "{{ maw_redis__cache_sync_container }}"
    pod: "{{ maw_redis__pod }}"
    image: "{{ maw_redis__cache_sync_image }}"
    env_file: "{{ maw_redis__cache_sync_envfile }}"
    state: started
    label:
      io.containers.autoupdate: image

- name: wait for maw-cache-sync container
  ansible.builtin.include_role:
    name: podman_wait_for_start
  vars:
    pod_start__container_name: "{{ maw_redis__cache_sync_container }}"
