---
- name: add ssh public keys
  become: yes
  ansible.builtin.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

# the following 2 tasks work in tandem:
#   the first will try to find the current user in the AllowUsers line
#   the second will add the user if grep returns 1 indicating the line did not match
- name: check if user is allowed in sshd_config
  become: yes
  ansible.builtin.command:
    argv:
      - grep
      - -E
      - '^AllowUsers.*\b{{ username }}\b.*$'
      - /etc/ssh/sshd_config
  ignore_errors: yes
  register: grep_allowusers

- name: add user to sshd AllowUsers
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    backup: yes
    backrefs: yes
    regex: "^AllowUsers\\s+(.*)$"
    line: "AllowUsers \\1 {{ username }}"
    state: present
    validate: sshd -t -f %s
  when:
    - grep_allowusers.rc == 1
  notify:
    - "reload_sshd"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: validate ssh
  delegate_to: localhost
  ansible.builtin.command:
    cmd: ssh {{ username }}@{{ ansible_host }} "echo success"
  register: validate_ssh_output
  changed_when: false

- name: validate ssh output
  ansible.builtin.fail:
    msg: Could not confirm SSH connectivity
  when: validate_ssh_output.stdout != "success"
  ignore_errors: "{{ ansible_check_mode }}"
