---
- name: add ssh public keys
  ansible.builtin.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

- name: validate ssh
  delegate_to: localhost
  ansible.builtin.command:
    cmd: ssh {{ username }}@{{ ansible_host }} "echo success"
  register: validate_ssh_output
  changed_when: false

- name: validate ssh output
  ansible.builtin.fail:
    msg: Could not confirm SSH connectivity
  when: validate_ssh_output.stdout != "success"
  ignore_errors: "{{ ansible_check_mode }}"

  - { key: "AllowUsers", value: "{{ username }}" }