---
# https://www.digitalocean.com/community/tutorials/how-to-harden-openssh-on-ubuntu-18-04
# https://www.cyberciti.biz/tips/linux-unix-bsd-openssh-server-best-practices.html
- name: harden ssh
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    backup: yes
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    validate: sshd -t -f %s
  loop: "{{ sshd_harden_items if sshd_harden_items is iterable else [] }}"
  notify:
    - "reload_sshd"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
