---
- name: install sshguard
  become: true
  ansible.builtin.dnf:
    name: sshguard
    state: latest
  tags: skip_ansible_lint

- name: enable sshguard whitelist
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sshguard.conf"
    backup: true
    regex: "^(#)?{{ item }}"
    line: "{{ item }}"
    state: present
  loop:
    - "WHITELIST_FILE=/etc/sshguard.whitelist"

- name: whitelist some addresses in sshguard
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sshguard.whitelist"
    backup: true
    regex: "^(#)?{{ item }}"
    line: "{{ item }}"
    state: present
  loop: "{{ sshd_sshguard_whitelist if sshd_sshguard_whitelist is iterable else [] }}"

- name: start and enable sshguard
  become: true
  ansible.builtin.service:
    name: sshguard
    enabled: true
    state: started
