---
- name: Install Packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - podman

- name: Enable linger for rootless containers
  become: true
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ _pod_init__linger_user }}
  loop_control:
    loop_var: _pod_init__linger_user
  loop: "{{ pod_init__linger_users }}"
