---
- name: Install Packages
  become: true
  ansible.builtin.dnf:
    state: present
    name:
      - podman

- name: Enable linger for rootless containers
  become: true
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ item.username }}
  when: item.enable_linger
  loop_control:
    label: "{{ item.username }}"
  loop: "{{ podman_users if podman_users is iterable else [] }}"
