---
- name: check if user is already in subuid (this can automatically be added when creating user)
  become: true
  ansible.builtin.command:
    argv:
      - grep
      - -E
      - '^{{ podman_user.username }}:.*$'
      - /etc/subuid
  ignore_errors: true
  register: grep_subuid

- name: Configure subuid and subgid
  become: true
  ansible.builtin.command:
    argv:
      - usermod
      - --add-subuids
      - "{{ podman_user.subuid }}"
      - --add-subgids
      - "{{ podman_user.subgid }}"
      - "{{ podman_user.username }}"
